/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, Image, Audio, Pdf, Video, FunctionLog } from
"@boundaryml/baml"
import { toBamlError, HTTPRequest, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {ActionPlanInput, ActionRunState, EvidenceRequirementVerification, EvidenceSlot, EvidenceVerification, EvidenceVerificationStatus, ExecutionDeltaOp, FastContextScoutCommand, FastContextScoutFileSelection, FastContextScoutPlannerDecision, InteractionRoute, InteractionRunMode, MemoryCandidate, MemoryConsolidationAction, MemoryConsolidationResult, MemoryLearningResult, MemoryWriteDecision, MemoryWriteResolutionResult, PlannedToolCall, PlannerActiveSkill, PlannerCurrentUserTurn, PlannerEvidenceMemoryItem, PlannerEvidenceRequirement, PlannerEvidenceStateItem, PlannerJournalItem, PlannerRoleplayPreset, PlannerRoleplayPresetDocument, PlannerStateCandidateTool, PlannerStateEffect, PlannerStateEvidence, PlannerStateEvidenceNeed, PlannerStateOpenQuestion, PlannerStateSnapshot, PlannerStateTargetRef, PlannerTimelineTurn, PlannerToolCallStateItem, ProgressSignals, RepeatedCallWarning, TaskCandidateTool, TaskEvidenceScope, TaskFrame, TaskRequiredEffect, TaskRequiredEvidence, TaskTargetRef, TaskUserInputNeed, ToolCallArgumentValue, ToolCallPlan, ToolCallStatus, ToolCapabilityFacets, ToolCapabilityItem, ToolCapabilityRisk, ToolCatalogItem, ToolCatalogSummaryItem, ToolEvidenceCapabilityItem, ToolLearningRecord, ToolLearningResult, TurnContextMode, TurnUnderstanding} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type TickReason = "Unknown";

type BamlCallOptions<EventsT = never> = {
tb?: TypeBuilder
clientRegistry?: ClientRegistry
client?: string
env?: Record<string, string | undefined>
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  events?: EventsT
  }

  export class AsyncHttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  async BuildTaskFrame(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "BuildTaskFrame",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ConsolidateMemoryCandidates(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ConsolidateMemoryCandidates",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async LearnMemory(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "LearnMemory",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async LearnToolUse(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "LearnToolUse",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async PlanFastContextScout(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "PlanFastContextScout",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async PlanToolCalls(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "PlanToolCalls",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairEvidenceVerification(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairEvidenceVerification",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairFastContextScoutPlan(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairFastContextScoutPlan",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairInteractionRoute(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairInteractionRoute",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairMemoryConsolidation(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairMemoryConsolidation",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairMemoryLearning(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairMemoryLearning",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairMemoryWriteResolution(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairMemoryWriteResolution",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairTaskFrame(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairTaskFrame",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairToolCallPlan(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairToolCallPlan",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairToolLearning(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairToolLearning",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RepairTurnUnderstanding(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RepairTurnUnderstanding",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ResolveMemoryWrite(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ResolveMemoryWrite",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RouteInteraction(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RouteInteraction",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async UnderstandUserTurn(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "UnderstandUserTurn",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async VerifyTaskEvidence(
  promptJson: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "VerifyTaskEvidence",
      {
      "promptJson": promptJson
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
      }

      export class AsyncHttpStreamRequest {
      constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

      
      async BuildTaskFrame(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "BuildTaskFrame",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ConsolidateMemoryCandidates(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ConsolidateMemoryCandidates",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async LearnMemory(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "LearnMemory",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async LearnToolUse(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "LearnToolUse",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async PlanFastContextScout(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "PlanFastContextScout",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async PlanToolCalls(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "PlanToolCalls",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairEvidenceVerification(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairEvidenceVerification",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairFastContextScoutPlan(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairFastContextScoutPlan",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairInteractionRoute(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairInteractionRoute",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairMemoryConsolidation(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairMemoryConsolidation",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairMemoryLearning(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairMemoryLearning",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairMemoryWriteResolution(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairMemoryWriteResolution",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairTaskFrame(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairTaskFrame",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairToolCallPlan(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairToolCallPlan",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairToolLearning(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairToolLearning",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RepairTurnUnderstanding(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RepairTurnUnderstanding",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ResolveMemoryWrite(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ResolveMemoryWrite",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RouteInteraction(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RouteInteraction",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async UnderstandUserTurn(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "UnderstandUserTurn",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async VerifyTaskEvidence(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "VerifyTaskEvidence",
          {
          "promptJson": promptJson
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
          }