/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type { partial_types } from "./partial_types.js"
import type * as types from "./types.js"
import type {ActionPlanInput, ActionRunState, AskUserDecision, AskUserDecisionKind, ContinuityAgendaDraft, ContinuityCapture, ContinuityCaptureItem, ContinuityRuleExtractionResult, ContinuityRuleItem, ConversationBoundary, DirectDecision, DirectDecisionKind, EvidenceSlot, ExecuteDecision, ExecuteDecisionKind, ExecutionDeltaOp, GoalMicroLoopCandidate, GoalMicroLoopDecision, GoalMicroLoopDecisionKind, PiConversationSummary, PiToolArgumentsDraft, PlanFragment, PlannedToolCall, PlannerActiveSkill, PlannerCurrentUserTurn, PlannerEvidenceMemoryItem, PlannerEvidenceRequirement, PlannerEvidenceStateItem, PlannerJournalItem, PlannerTimelineTurn, PlannerToolCallStateItem, ProgressSignals, RepeatedCallWarning, ResidentIdleDecision, ResidentIdleDecisionKind, ResidentIdleGoalProposal, ResidentSpeechProjection, TemporalMemoryDigest, TemporalMemoryTextPart, ToolCallArgumentValue, ToolCallStatus, ToolCapabilityFacets, ToolCapabilityItem, ToolCapabilityRisk, ToolCatalogItem, ToolCatalogSummaryItem, ToolEvidenceCapabilityItem, ToolLearningRecord, ToolLearningResult, ToolRiskAudit, ToolRiskAuditDecision, ToolRiskLevel} from "./types.js"
import type TypeBuilder from "./type_builder.js"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AuditToolRisk(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ToolRiskAudit {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "AuditToolRisk",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ToolRiskAudit
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ClassifyConversationBoundary(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ConversationBoundary {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ClassifyConversationBoundary",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ConversationBoundary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DecideGoalMicroLoop(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.GoalMicroLoopDecision[] {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "DecideGoalMicroLoop",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.GoalMicroLoopDecision[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DecideResidentIdle(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ResidentIdleDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "DecideResidentIdle",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ResidentIdleDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EvolveTurn(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.DirectDecision | types.AskUserDecision | types.ExecuteDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "EvolveTurn",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.DirectDecision | types.AskUserDecision | types.ExecuteDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityFacts(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ContinuityCapture {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ExtractContinuityFacts",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ContinuityCapture
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityRules(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ContinuityRuleExtractionResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ExtractContinuityRules",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ContinuityRuleExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  FillPiToolArguments(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.PiToolArgumentsDraft {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "FillPiToolArguments",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.PiToolArgumentsDraft
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  LearnToolUse(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ToolLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "LearnToolUse",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ToolLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ProjectResidentSpeech(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ResidentSpeechProjection {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ProjectResidentSpeech",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ResidentSpeechProjection
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityFacts(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ContinuityCapture {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairContinuityFacts",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ContinuityCapture
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityRules(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ContinuityRuleExtractionResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairContinuityRules",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ContinuityRuleExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairControllerDecision(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.DirectDecision | types.AskUserDecision | types.ExecuteDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairControllerDecision",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.DirectDecision | types.AskUserDecision | types.ExecuteDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiConversationSummary(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.PiConversationSummary {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairPiConversationSummary",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.PiConversationSummary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiToolArguments(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.PiToolArgumentsDraft {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairPiToolArguments",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.PiToolArgumentsDraft
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolLearning(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ToolLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolLearning",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ToolLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolRiskAudit(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ToolRiskAudit {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolRiskAudit",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ToolRiskAudit
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizePiConversation(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.PiConversationSummary {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "SummarizePiConversation",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.PiConversationSummary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeTemporalMemory(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.TemporalMemoryDigest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "SummarizeTemporalMemory",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.TemporalMemoryDigest
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AuditToolRisk(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ToolRiskAudit {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "AuditToolRisk",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ToolRiskAudit
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ClassifyConversationBoundary(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ConversationBoundary {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ClassifyConversationBoundary",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ConversationBoundary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DecideGoalMicroLoop(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.GoalMicroLoopDecision[] {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "DecideGoalMicroLoop",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.GoalMicroLoopDecision[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DecideResidentIdle(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ResidentIdleDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "DecideResidentIdle",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ResidentIdleDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EvolveTurn(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.DirectDecision | partial_types.AskUserDecision | partial_types.ExecuteDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "EvolveTurn",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.DirectDecision | partial_types.AskUserDecision | partial_types.ExecuteDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityFacts(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ContinuityCapture {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ExtractContinuityFacts",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ContinuityCapture
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityRules(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ContinuityRuleExtractionResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ExtractContinuityRules",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ContinuityRuleExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  FillPiToolArguments(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.PiToolArgumentsDraft {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "FillPiToolArguments",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.PiToolArgumentsDraft
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  LearnToolUse(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ToolLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "LearnToolUse",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ToolLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ProjectResidentSpeech(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ResidentSpeechProjection {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ProjectResidentSpeech",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ResidentSpeechProjection
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityFacts(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ContinuityCapture {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairContinuityFacts",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ContinuityCapture
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityRules(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ContinuityRuleExtractionResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairContinuityRules",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ContinuityRuleExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairControllerDecision(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.DirectDecision | partial_types.AskUserDecision | partial_types.ExecuteDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairControllerDecision",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.DirectDecision | partial_types.AskUserDecision | partial_types.ExecuteDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiConversationSummary(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.PiConversationSummary {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairPiConversationSummary",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.PiConversationSummary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiToolArguments(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.PiToolArgumentsDraft {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairPiToolArguments",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.PiToolArgumentsDraft
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolLearning(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ToolLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolLearning",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ToolLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolRiskAudit(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ToolRiskAudit {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolRiskAudit",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ToolRiskAudit
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizePiConversation(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.PiConversationSummary {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "SummarizePiConversation",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.PiConversationSummary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeTemporalMemory(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.TemporalMemoryDigest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "SummarizeTemporalMemory",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.TemporalMemoryDigest
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}