/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type { partial_types } from "./partial_types.js"
import type * as types from "./types.js"
import type {ActionPlanInput, ActionRunState, AskUserDecision, AskUserDecisionKind, DirectDecision, DirectDecisionKind, EvidenceSlot, ExecuteDecision, ExecuteDecisionKind, ExecutionDeltaOp, GroundedDigest, GroundedDigestEntry, MemoryCandidate, MemoryConsolidationAction, MemoryConsolidationResult, MemoryLearningResult, MemoryWriteDecision, MemoryWriteResolutionResult, PiToolArgumentsDraft, PlanFragment, PlannedToolCall, PlannerActiveSkill, PlannerCurrentUserTurn, PlannerEvidenceMemoryItem, PlannerEvidenceRequirement, PlannerEvidenceStateItem, PlannerJournalItem, PlannerRoleplayPreset, PlannerRoleplayPresetDocument, PlannerTimelineTurn, PlannerToolCallStateItem, ProgressSignals, RepeatedCallWarning, ToolCallArgumentValue, ToolCallStatus, ToolCapabilityFacets, ToolCapabilityItem, ToolCapabilityRisk, ToolCatalogItem, ToolCatalogSummaryItem, ToolEvidenceCapabilityItem, ToolLearningRecord, ToolLearningResult, ToolRiskAudit, ToolRiskAuditDecision, ToolRiskLevel} from "./types.js"
import type TypeBuilder from "./type_builder.js"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AuditToolRisk(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ToolRiskAudit {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "AuditToolRisk",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ToolRiskAudit
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  CondenseToolObservations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.GroundedDigest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "CondenseToolObservations",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.GroundedDigest
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ConsolidateMemoryCandidates(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.MemoryConsolidationResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ConsolidateMemoryCandidates",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.MemoryConsolidationResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EvolveTurn(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.DirectDecision | types.AskUserDecision | types.ExecuteDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "EvolveTurn",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.DirectDecision | types.AskUserDecision | types.ExecuteDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  FillPiToolArguments(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.PiToolArgumentsDraft {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "FillPiToolArguments",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.PiToolArgumentsDraft
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  LearnMemory(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.MemoryLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "LearnMemory",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.MemoryLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  LearnToolUse(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ToolLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "LearnToolUse",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ToolLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairControllerDecision(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.DirectDecision | types.AskUserDecision | types.ExecuteDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairControllerDecision",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.DirectDecision | types.AskUserDecision | types.ExecuteDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairMemoryConsolidation(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.MemoryConsolidationResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairMemoryConsolidation",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.MemoryConsolidationResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairMemoryLearning(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.MemoryLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairMemoryLearning",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.MemoryLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairMemoryWriteResolution(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.MemoryWriteResolutionResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairMemoryWriteResolution",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.MemoryWriteResolutionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiToolArguments(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.PiToolArgumentsDraft {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairPiToolArguments",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.PiToolArgumentsDraft
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolLearning(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ToolLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolLearning",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ToolLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolObservationDigest(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.GroundedDigest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolObservationDigest",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.GroundedDigest
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolRiskAudit(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ToolRiskAudit {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolRiskAudit",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ToolRiskAudit
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ResolveMemoryWrite(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.MemoryWriteResolutionResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ResolveMemoryWrite",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.MemoryWriteResolutionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AuditToolRisk(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ToolRiskAudit {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "AuditToolRisk",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ToolRiskAudit
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  CondenseToolObservations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.GroundedDigest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "CondenseToolObservations",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.GroundedDigest
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ConsolidateMemoryCandidates(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.MemoryConsolidationResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ConsolidateMemoryCandidates",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.MemoryConsolidationResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EvolveTurn(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.DirectDecision | partial_types.AskUserDecision | partial_types.ExecuteDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "EvolveTurn",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.DirectDecision | partial_types.AskUserDecision | partial_types.ExecuteDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  FillPiToolArguments(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.PiToolArgumentsDraft {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "FillPiToolArguments",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.PiToolArgumentsDraft
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  LearnMemory(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.MemoryLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "LearnMemory",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.MemoryLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  LearnToolUse(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ToolLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "LearnToolUse",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ToolLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairControllerDecision(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.DirectDecision | partial_types.AskUserDecision | partial_types.ExecuteDecision {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairControllerDecision",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.DirectDecision | partial_types.AskUserDecision | partial_types.ExecuteDecision
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairMemoryConsolidation(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.MemoryConsolidationResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairMemoryConsolidation",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.MemoryConsolidationResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairMemoryLearning(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.MemoryLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairMemoryLearning",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.MemoryLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairMemoryWriteResolution(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.MemoryWriteResolutionResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairMemoryWriteResolution",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.MemoryWriteResolutionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiToolArguments(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.PiToolArgumentsDraft {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairPiToolArguments",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.PiToolArgumentsDraft
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolLearning(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ToolLearningResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolLearning",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ToolLearningResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolObservationDigest(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.GroundedDigest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolObservationDigest",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.GroundedDigest
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolRiskAudit(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ToolRiskAudit {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "RepairToolRiskAudit",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ToolRiskAudit
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ResolveMemoryWrite(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.MemoryWriteResolutionResult {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "ResolveMemoryWrite",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.MemoryWriteResolutionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}