/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  ActionPlanInput,  ActionRunState,  EvidenceSlot,  ExecutionDeltaOp,  InteractionPreparation,  InteractionRoute,  InteractionRunMode,  MemoryCandidate,  MemoryConsolidationAction,  MemoryConsolidationResult,  MemoryLearningResult,  MemoryWriteDecision,  MemoryWriteResolutionResult,  PiCompactionDecision,  PiCompactionSummary,  PiControllerAction,  PiControllerActionKind,  PiPlannedToolCall,  PiToolArgumentsDraft,  PlannerActiveSkill,  PlannerCurrentUserTurn,  PlannerEvidenceMemoryItem,  PlannerEvidenceRequirement,  PlannerEvidenceStateItem,  PlannerJournalItem,  PlannerRoleplayPreset,  PlannerRoleplayPresetDocument,  PlannerTimelineTurn,  PlannerToolCallStateItem,  ProgressSignals,  RepeatedCallWarning,  ToolCallArgumentValue,  ToolCallStatus,  ToolCapabilityFacets,  ToolCapabilityItem,  ToolCapabilityRisk,  ToolCatalogItem,  ToolCatalogSummaryItem,  ToolEvidenceCapabilityItem,  ToolLearningRecord,  ToolLearningResult,  ToolRiskAudit,  ToolRiskAuditDecision,  ToolRiskLevel,  TurnContextMode,  TurnUnderstanding } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface ActionPlanInput {
      currentUserTurn?: PlannerCurrentUserTurn | null
      turnUnderstanding?: TurnUnderstanding | null
      roleplayPreset?: PlannerRoleplayPreset | null
      runState?: ActionRunState | null
      timeline: PlannerTimelineTurn[]
      evidenceMemory: PlannerEvidenceMemoryItem[]
      evidenceState: PlannerEvidenceStateItem[]
      plannerJournal: PlannerJournalItem[]
      toolTagCatalog: string[]
      compactToolCatalog: ToolCatalogSummaryItem[]
      toolCatalog: ToolCatalogItem[]
      activeSkills: PlannerActiveSkill[]
    }
    export interface ActionRunState {
      currentStep?: number | null
      dynamicTools?: boolean | null
      loadedTools: string[]
      progress?: ProgressSignals | null
      warnings: RepeatedCallWarning[]
      calls: PlannerToolCallStateItem[]
    }
    export interface EvidenceSlot {
      name?: string | null
      value?: string | null
    }
    export interface InteractionPreparation {
      turnUnderstanding?: TurnUnderstanding | null
      initialAction?: PiControllerAction | null
    }
    export interface InteractionRoute {
      mode?: types.InteractionRunMode | null
      objective?: string | null
      preferredTools: string[]
      discoveryQueries: string[]
    }
    export interface MemoryCandidate {
      type?: string | null
      subject?: string | null
      claim?: string | null
      howToApply?: string | null
      tags: string[]
      triggers: string[]
      sourceRefs: string[]
      reason?: string | null
      confidence?: number | null
    }
    export interface MemoryConsolidationAction {
      operation?: string | null
      type?: string | null
      subject?: string | null
      claim?: string | null
      howToApply?: string | null
      tags: string[]
      triggers: string[]
      sourceRefs: string[]
      candidateUris: string[]
      targetMemoryUri?: string | null
      reason?: string | null
      confidence?: number | null
    }
    export interface MemoryConsolidationResult {
      actions: MemoryConsolidationAction[]
    }
    export interface MemoryLearningResult {
      candidates: MemoryCandidate[]
    }
    export interface MemoryWriteDecision {
      operation?: string | null
      type?: string | null
      subject?: string | null
      claim?: string | null
      howToApply?: string | null
      tags: string[]
      triggers: string[]
      sourceRefs: string[]
      candidateUris: string[]
      targetMemoryUri?: string | null
      reason?: string | null
      confidence?: number | null
    }
    export interface MemoryWriteResolutionResult {
      decision?: MemoryWriteDecision | null
    }
    export interface PiCompactionDecision {
      decision?: string | null
      rationale?: string | null
    }
    export interface PiCompactionSummary {
      goals: string[]
      constraints: string[]
      completed: string[]
      inProgress: string[]
      blocked: string[]
      decisions: PiCompactionDecision[]
      nextSteps: string[]
      criticalContext: string[]
    }
    export interface PiControllerAction {
      kind?: types.PiControllerActionKind | null
      answerPlan?: string[] | null
      question?: string | null
      preface?: string | null
      calls?: PiPlannedToolCall[] | null
    }
    export interface PiPlannedToolCall {
      toolName?: string | null
      purpose?: string | null
      required?: boolean | null
      dependsOn?: number[] | null
      argumentHints?: Record<string, ToolCallArgumentValue> | null
    }
    export interface PiToolArgumentsDraft {
      arguments: Record<string, ToolCallArgumentValue>
      missingInputs: string[]
      assumptions: string[]
    }
    export interface PlannerActiveSkill {
      name?: string | null
      title?: string | null
      summary?: string | null
      useCases: string[]
      avoid: string[]
      recommendedTools: string[]
      evidenceRequirements: PlannerEvidenceRequirement[]
    }
    export interface PlannerCurrentUserTurn {
      requestId?: string | null
      content?: string | null
    }
    export interface PlannerEvidenceMemoryItem {
      evidenceUri?: string | null
      kind?: string | null
      locator?: string | null
      display?: string | null
      label?: string | null
      toolName?: string | null
      artifactUri?: string | null
      facts: EvidenceSlot[]
      artifactRefs: string[]
    }
    export interface PlannerEvidenceRequirement {
      need?: string | null
      accepts: string[]
      minimumQuality: string[]
      minimum?: number | null
      purpose?: string | null
    }
    export interface PlannerEvidenceStateItem {
      evidenceUri?: string | null
      kind?: string | null
      toolName?: string | null
      artifactUri?: string | null
      locator?: string | null
      display?: string | null
      label?: string | null
      source?: string | null
      confidence?: number | null
      facts: EvidenceSlot[]
      artifactRefs: string[]
    }
    export interface PlannerJournalItem {
      requestId?: string | null
      step?: number | null
      selectedAction?: string | null
      evidenceUris: string[]
      artifactUris: string[]
      loadedTools: string[]
      outcome?: string | null
    }
    export interface PlannerRoleplayPreset {
      enabled?: boolean | null
      activePresetName?: string | null
      documents: PlannerRoleplayPresetDocument[]
    }
    export interface PlannerRoleplayPresetDocument {
      name?: string | null
      format?: string | null
      title?: string | null
      updatedAt?: string | null
      content?: string | null
    }
    export interface PlannerTimelineTurn {
      index?: number | null
      role?: string | null
      kind?: string | null
      step?: number | null
      content?: string | null
      payloadJson?: string | null
      evidenceUris: string[]
      artifactUris: string[]
    }
    export interface PlannerToolCallStateItem {
      step?: number | null
      toolName?: string | null
      status?: types.ToolCallStatus | null
      artifactUri?: string | null
      evidenceUris: string[]
      resultKind?: string | null
      argumentsPreview?: string | null
      error?: string | null
    }
    export interface ProgressSignals {
      totalToolCalls?: number | null
      totalEvidence?: number | null
      lastNewEvidenceStep?: number | null
      repeatedCallCount?: number | null
      stalled?: boolean | null
    }
    export interface RepeatedCallWarning {
      toolName?: string | null
      argsHash?: string | null
      count?: number | null
      lastStep?: number | null
    }
    export interface ToolCapabilityFacets {
      Actions?: string[] | null
      Targets?: string[] | null
      Inputs?: string[] | null
      Outputs?: string[] | null
      Evidence?: string[] | null
      Effects?: string[] | null
    }
    export interface ToolCapabilityItem {
      id?: string | null
      title?: string | null
      description?: string | null
      facets?: ToolCapabilityFacets | null
      risk?: ToolCapabilityRisk | null
    }
    export interface ToolCapabilityRisk {
      sideEffect?: string | null
      permission?: string | null
    }
    export interface ToolCatalogItem {
      name?: string | null
      title?: string | null
      summary?: string | null
      capabilities: ToolCapabilityItem[]
      tags: string[]
      useCases: string[]
      examples: string[]
      avoid: string[]
      permissions: string[]
      evidenceCapabilities: ToolEvidenceCapabilityItem[]
      loaded?: boolean | null
    }
    export interface ToolCatalogSummaryItem {
      name?: string | null
      title?: string | null
      summary?: string | null
      capabilities: string[]
      evidence: string[]
      effects: string[]
      outputs: string[]
      permissions: string[]
      loaded?: boolean | null
      rootKind?: string | null
    }
    export interface ToolEvidenceCapabilityItem {
      produces?: string | null
      quality?: string | null
      satisfies: string[]
      kinds: string[]
      capabilityIds: string[]
    }
    export interface ToolLearningRecord {
      toolName?: string | null
      tags: string[]
      sourceTerms: string[]
      triggers: string[]
      reason?: string | null
      confidence?: number | null
    }
    export interface ToolLearningResult {
      records: ToolLearningRecord[]
    }
    export interface ToolRiskAudit {
      decision?: types.ToolRiskAuditDecision | null
      riskLevel?: types.ToolRiskLevel | null
      confidence?: number | null
      tripwire?: boolean | null
      reason?: string | null
      matchedConcerns: string[]
      safeAlternative?: string | null
    }
    export interface TurnUnderstanding {
      rawUserTurn?: string | null
      standaloneRequest?: string | null
      contextMode?: types.TurnContextMode | null
      contextBasis?: string | null
      missingContext?: string | null
    }
export interface ToolCallArgumentValue {
  [key: string]: string | number | boolean | ToolCallArgumentValue[] | Record<string, ToolCallArgumentValue> | null
}

}