/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  ActionDecision,  ActionKind,  ActionPlanInput,  ActionRuntime,  ActionTask,  EvidenceRecord,  ExecutionDelta,  ExecutionDeltaOp,  ExecutionState,  ProgressSignals,  RepeatedCallWarning,  ToolCallRecord,  ToolCallStatus,  ToolCatalogItem } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface ActionDecision {
      action?: types.ActionKind | null
      intent?: string | null
      progressAssessment?: string | null
      nextStepGoal?: string | null
      requiredCapabilities: string[]
      toolSearchQueries: string[]
      preferredTools: string[]
      confidence?: number | null
      instructionToMainModel?: string | null
    }
    export interface ActionPlanInput {
      task?: ActionTask | null
      runtime?: ActionRuntime | null
      executionState?: ExecutionState | null
      recentDeltas: ExecutionDelta[]
      toolCatalog: ToolCatalogItem[]
    }
    export interface ActionRuntime {
      currentStep?: number | null
      dynamicTools?: boolean | null
      loadedTools: string[]
    }
    export interface ActionTask {
      userMessage?: string | null
    }
    export interface EvidenceRecord {
      key?: string | null
      kind?: string | null
      label?: string | null
      artifactId?: string | null
      source?: string | null
    }
    export interface ExecutionDelta {
      step?: number | null
      op?: types.ExecutionDeltaOp | null
      key?: string | null
      toolName?: string | null
      argsHash?: string | null
      status?: types.ToolCallStatus | null
      artifactId?: string | null
      evidenceKeys: string[]
      note?: string | null
    }
    export interface ExecutionState {
      calls: ToolCallRecord[]
      evidence: EvidenceRecord[]
      warnings: RepeatedCallWarning[]
      progress?: ProgressSignals | null
    }
    export interface ProgressSignals {
      totalToolCalls?: number | null
      totalEvidence?: number | null
      lastNewEvidenceStep?: number | null
      repeatedCallCount?: number | null
      stalled?: boolean | null
    }
    export interface RepeatedCallWarning {
      toolName?: string | null
      argsHash?: string | null
      count?: number | null
      lastStep?: number | null
    }
    export interface ToolCallRecord {
      step?: number | null
      toolName?: string | null
      argsHash?: string | null
      status?: types.ToolCallStatus | null
      artifactId?: string | null
      evidenceKeys: string[]
      error?: string | null
    }
    export interface ToolCatalogItem {
      name?: string | null
      title?: string | null
      summary?: string | null
      tags: string[]
      useCases: string[]
      examples: string[]
      avoid: string[]
      permissions: string[]
      loaded?: boolean | null
    }
}