/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  ActionPlanInput,  ActionRunState,  EvidenceRequirementVerification,  EvidenceSlot,  EvidenceVerification,  EvidenceVerificationStatus,  ExecutionDeltaOp,  FastContextScoutCommand,  FastContextScoutFileSelection,  FastContextScoutPlannerDecision,  InteractionRoute,  InteractionRunMode,  MemoryCandidate,  MemoryConsolidationAction,  MemoryConsolidationResult,  MemoryLearningResult,  MemoryWriteDecision,  MemoryWriteResolutionResult,  PlannedToolCall,  PlannerActiveSkill,  PlannerCurrentUserTurn,  PlannerEvidenceMemoryItem,  PlannerEvidenceRequirement,  PlannerEvidenceStateItem,  PlannerJournalItem,  PlannerRoleplayPreset,  PlannerRoleplayPresetDocument,  PlannerStateCandidateTool,  PlannerStateEffect,  PlannerStateEvidence,  PlannerStateEvidenceNeed,  PlannerStateOpenQuestion,  PlannerStateSnapshot,  PlannerStateTargetRef,  PlannerTimelineTurn,  PlannerToolCallStateItem,  ProgressSignals,  RepeatedCallWarning,  TaskCandidateTool,  TaskEvidenceScope,  TaskFrame,  TaskRequiredEffect,  TaskRequiredEvidence,  TaskTargetRef,  TaskUserInputNeed,  ToolCallArgumentValue,  ToolCallPlan,  ToolCallStatus,  ToolCapabilityFacets,  ToolCapabilityItem,  ToolCapabilityRisk,  ToolCatalogItem,  ToolCatalogSummaryItem,  ToolEvidenceCapabilityItem,  ToolLearningRecord,  ToolLearningResult,  TurnContextMode,  TurnUnderstanding } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface ActionPlanInput {
      currentUserTurn?: PlannerCurrentUserTurn | null
      turnUnderstanding?: TurnUnderstanding | null
      roleplayPreset?: PlannerRoleplayPreset | null
      runState?: ActionRunState | null
      timeline: PlannerTimelineTurn[]
      evidenceMemory: PlannerEvidenceMemoryItem[]
      evidenceState: PlannerEvidenceStateItem[]
      plannerJournal: PlannerJournalItem[]
      plannerState?: PlannerStateSnapshot | null
      toolTagCatalog: string[]
      compactToolCatalog: ToolCatalogSummaryItem[]
      toolCatalog: ToolCatalogItem[]
      activeSkills: PlannerActiveSkill[]
    }
    export interface ActionRunState {
      currentStep?: number | null
      dynamicTools?: boolean | null
      loadedTools: string[]
      progress?: ProgressSignals | null
      warnings: RepeatedCallWarning[]
      calls: PlannerToolCallStateItem[]
    }
    export interface EvidenceRequirementVerification {
      requirementId?: string | null
      need?: string | null
      status?: types.EvidenceVerificationStatus | null
      evidenceUris: string[]
      artifactUris: string[]
      reason?: string | null
      missingFacts: string[]
      unsupportedClaims: string[]
    }
    export interface EvidenceSlot {
      name?: string | null
      value?: string | null
    }
    export interface EvidenceVerification {
      ready?: boolean | null
      requirements: EvidenceRequirementVerification[]
      summary?: string | null
    }
    export interface FastContextScoutCommand {
      type?: string | null
      pattern?: string | null
      path?: string | null
      include?: string[] | null
      exclude?: string[] | null
      regex?: boolean | null
      caseSensitive?: boolean | null
      startLine?: number | null
      endLine?: number | null
      depth?: number | null
    }
    export interface FastContextScoutFileSelection {
      path?: string | null
      startLine?: number | null
      endLine?: number | null
      reason?: string | null
    }
    export interface FastContextScoutPlannerDecision {
      action?: string | null
      commands: FastContextScoutCommand[]
      files: FastContextScoutFileSelection[]
      reason?: string | null
    }
    export interface InteractionRoute {
      mode?: types.InteractionRunMode | null
      objective?: string | null
      needsFreshEvidence?: boolean | null
      needsWorkspaceRead?: boolean | null
      needsSideEffect?: boolean | null
      risk?: string | null
      preferredTools: string[]
      discoveryQueries: string[]
      reason?: string | null
    }
    export interface MemoryCandidate {
      type?: string | null
      subject?: string | null
      claim?: string | null
      howToApply?: string | null
      tags: string[]
      triggers: string[]
      sourceRefs: string[]
      reason?: string | null
      confidence?: number | null
    }
    export interface MemoryConsolidationAction {
      operation?: string | null
      type?: string | null
      subject?: string | null
      claim?: string | null
      howToApply?: string | null
      tags: string[]
      triggers: string[]
      sourceRefs: string[]
      candidateUris: string[]
      targetMemoryUri?: string | null
      reason?: string | null
      confidence?: number | null
    }
    export interface MemoryConsolidationResult {
      actions: MemoryConsolidationAction[]
    }
    export interface MemoryLearningResult {
      candidates: MemoryCandidate[]
    }
    export interface MemoryWriteDecision {
      operation?: string | null
      type?: string | null
      subject?: string | null
      claim?: string | null
      howToApply?: string | null
      tags: string[]
      triggers: string[]
      sourceRefs: string[]
      candidateUris: string[]
      targetMemoryUri?: string | null
      reason?: string | null
      confidence?: number | null
    }
    export interface MemoryWriteResolutionResult {
      decision?: MemoryWriteDecision | null
    }
    export interface PlannedToolCall {
      name?: string | null
      arguments: Record<string, ToolCallArgumentValue>
    }
    export interface PlannerActiveSkill {
      name?: string | null
      title?: string | null
      summary?: string | null
      useCases: string[]
      avoid: string[]
      recommendedTools: string[]
      evidenceRequirements: PlannerEvidenceRequirement[]
    }
    export interface PlannerCurrentUserTurn {
      requestId?: string | null
      content?: string | null
    }
    export interface PlannerEvidenceMemoryItem {
      evidenceUri?: string | null
      kind?: string | null
      locator?: string | null
      display?: string | null
      label?: string | null
      toolName?: string | null
      artifactUri?: string | null
      facts: EvidenceSlot[]
      artifactRefs: string[]
    }
    export interface PlannerEvidenceRequirement {
      need?: string | null
      accepts: string[]
      minimumQuality: string[]
      minimum?: number | null
      purpose?: string | null
    }
    export interface PlannerEvidenceStateItem {
      evidenceUri?: string | null
      kind?: string | null
      toolName?: string | null
      artifactUri?: string | null
      locator?: string | null
      display?: string | null
      label?: string | null
      source?: string | null
      confidence?: number | null
      facts: EvidenceSlot[]
      artifactRefs: string[]
    }
    export interface PlannerJournalItem {
      requestId?: string | null
      step?: number | null
      selectedAction?: string | null
      evidenceUris: string[]
      artifactUris: string[]
      loadedTools: string[]
      outcome?: string | null
    }
    export interface PlannerRoleplayPreset {
      enabled?: boolean | null
      activePresetName?: string | null
      documents: PlannerRoleplayPresetDocument[]
    }
    export interface PlannerRoleplayPresetDocument {
      name?: string | null
      format?: string | null
      title?: string | null
      updatedAt?: string | null
      content?: string | null
    }
    export interface PlannerStateCandidateTool {
      name?: string | null
      purpose?: string | null
      supports: string[]
    }
    export interface PlannerStateEffect {
      id?: string | null
      effect?: string | null
      target?: string | null
      reason?: string | null
    }
    export interface PlannerStateEvidence {
      evidenceUri?: string | null
      kind?: string | null
      toolName?: string | null
      artifactUri?: string | null
      locator?: string | null
      display?: string | null
      label?: string | null
    }
    export interface PlannerStateEvidenceNeed {
      id?: string | null
      need?: string | null
      scope?: string | null
      minimum?: number | null
      reason?: string | null
    }
    export interface PlannerStateOpenQuestion {
      question?: string | null
      reason?: string | null
    }
    export interface PlannerStateSnapshot {
      taskId?: string | null
      requestId?: string | null
      step?: number | null
      status?: string | null
      userGoal?: string | null
      currentIntent?: string | null
      intentTags: string[]
      taskTags: string[]
      targetRefs: PlannerStateTargetRef[]
      requiredEffects: PlannerStateEffect[]
      evidenceNeeds: PlannerStateEvidenceNeed[]
      completedEvidence: PlannerStateEvidence[]
      completedEffects: PlannerStateEffect[]
      openQuestions: PlannerStateOpenQuestion[]
      candidateTools: PlannerStateCandidateTool[]
      discoveryQueries: string[]
      nextStepPurpose?: string | null
      completionCriteria: string[]
      lastAction?: string | null
      loadedTools: string[]
      recentCalls: PlannerToolCallStateItem[]
      updatedAt?: string | null
    }
    export interface PlannerStateTargetRef {
      kind?: string | null
      value?: string | null
      status?: string | null
    }
    export interface PlannerTimelineTurn {
      index?: number | null
      role?: string | null
      kind?: string | null
      step?: number | null
      content?: string | null
      payloadJson?: string | null
      evidenceUris: string[]
      artifactUris: string[]
    }
    export interface PlannerToolCallStateItem {
      step?: number | null
      toolName?: string | null
      status?: types.ToolCallStatus | null
      artifactUri?: string | null
      evidenceUris: string[]
      resultKind?: string | null
      argumentsPreview?: string | null
      error?: string | null
    }
    export interface ProgressSignals {
      totalToolCalls?: number | null
      totalEvidence?: number | null
      lastNewEvidenceStep?: number | null
      repeatedCallCount?: number | null
      stalled?: boolean | null
    }
    export interface RepeatedCallWarning {
      toolName?: string | null
      argsHash?: string | null
      count?: number | null
      lastStep?: number | null
    }
    export interface TaskCandidateTool {
      name?: string | null
      purpose?: string | null
      supports: string[]
    }
    export interface TaskFrame {
      taskType?: string | null
      answerGoal?: string | null
      intentTags: string[]
      taskTags: string[]
      targetRefs: TaskTargetRef[]
      candidateTools: TaskCandidateTool[]
      discoveryQueries: string[]
      requiredEffects: TaskRequiredEffect[]
      requiredEvidence: TaskRequiredEvidence[]
      userInputNeeds: TaskUserInputNeed[]
      nextStepPurpose?: string | null
      completionCriteria: string[]
      notes: string[]
    }
    export interface TaskRequiredEffect {
      id?: string | null
      effect?: string | null
      target?: string | null
      proof?: string | null
      reason?: string | null
    }
    export interface TaskRequiredEvidence {
      id?: string | null
      need?: string | null
      scope?: types.TaskEvidenceScope | null
      minimum?: number | null
      reason?: string | null
    }
    export interface TaskTargetRef {
      kind?: string | null
      value?: string | null
      status?: string | null
    }
    export interface TaskUserInputNeed {
      question?: string | null
      reason?: string | null
    }
    export interface ToolCallPlan {
      calls: PlannedToolCall[]
    }
    export interface ToolCapabilityFacets {
      Actions?: string[] | null
      Targets?: string[] | null
      Inputs?: string[] | null
      Outputs?: string[] | null
      Evidence?: string[] | null
      Effects?: string[] | null
    }
    export interface ToolCapabilityItem {
      id?: string | null
      title?: string | null
      description?: string | null
      facets?: ToolCapabilityFacets | null
      risk?: ToolCapabilityRisk | null
    }
    export interface ToolCapabilityRisk {
      sideEffect?: string | null
      permission?: string | null
    }
    export interface ToolCatalogItem {
      name?: string | null
      title?: string | null
      summary?: string | null
      capabilities: ToolCapabilityItem[]
      tags: string[]
      useCases: string[]
      examples: string[]
      avoid: string[]
      permissions: string[]
      evidenceCapabilities: ToolEvidenceCapabilityItem[]
      loaded?: boolean | null
    }
    export interface ToolCatalogSummaryItem {
      name?: string | null
      title?: string | null
      summary?: string | null
      capabilities: string[]
      evidence: string[]
      effects: string[]
      outputs: string[]
      permissions: string[]
      loaded?: boolean | null
      rootKind?: string | null
    }
    export interface ToolEvidenceCapabilityItem {
      produces?: string | null
      quality?: string | null
      satisfies: string[]
      kinds: string[]
      capabilityIds: string[]
    }
    export interface ToolLearningRecord {
      toolName?: string | null
      tags: string[]
      sourceTerms: string[]
      triggers: string[]
      reason?: string | null
      confidence?: number | null
    }
    export interface ToolLearningResult {
      records: ToolLearningRecord[]
    }
    export interface TurnUnderstanding {
      rawUserTurn?: string | null
      standaloneRequest?: string | null
      contextMode?: types.TurnContextMode | null
      contextBasis?: string | null
      missingContext?: string | null
    }
export interface ToolCallArgumentValue {
  [key: string]: string | number | boolean | ToolCallArgumentValue[] | Record<string, ToolCallArgumentValue> | null
}

}