/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, Image, Audio, Pdf, Video, Collector, FunctionLog } from "@boundaryml/baml"
import { toBamlError, BamlAbortError, ClientRegistry, type HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types.js"
import type * as types from "./types.js"
import type {ActionPlanInput, ActionRunState, AskUserDecision, AskUserDecisionKind, ContinuityAgendaDraft, ContinuityCapture, ContinuityCaptureItem, ContinuityRuleExtractionResult, ContinuityRuleItem, ConversationBoundary, DirectDecision, DirectDecisionKind, EvidenceSlot, ExecuteDecision, ExecuteDecisionKind, ExecutionDeltaOp, GoalMicroLoopCandidate, GoalMicroLoopDecision, GoalMicroLoopDecisionKind, PiConversationSummary, PiToolArgumentsDraft, PlanFragment, PlannedToolCall, PlannerActiveSkill, PlannerCurrentUserTurn, PlannerEvidenceMemoryItem, PlannerEvidenceRequirement, PlannerEvidenceStateItem, PlannerJournalItem, PlannerTimelineTurn, PlannerToolCallStateItem, ProgressSignals, RepeatedCallWarning, ResidentIdleDecision, ResidentIdleDecisionKind, ResidentIdleGoalProposal, ResidentSpeechProjection, TemporalMemoryDigest, ToolCallArgumentValue, ToolCallStatus, ToolCapabilityFacets, ToolCapabilityItem, ToolCapabilityRisk, ToolCatalogItem, ToolCatalogSummaryItem, ToolEvidenceCapabilityItem, ToolLearningRecord, ToolLearningResult, ToolRiskAudit, ToolRiskAuditDecision, ToolRiskLevel} from "./types.js"
import type TypeBuilder from "./type_builder.js"
import { HttpRequest, HttpStreamRequest } from "./sync_request.js"
import { LlmResponseParser, LlmStreamParser } from "./parser.js"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals.js"
import type * as events from "./events.js"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 * Example:
 * ```ts
 * import { RecursivePartialNull } from './baml_client/types.js'
 * ```
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>;

type TickReason = "Unknown";

type BamlCallOptions<WatchersT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  client?: string
  collector?: Collector | Collector[]
  env?: Record<string, string | undefined>
  tags?: Record<string, string>
  signal?: AbortSignal
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  watchers?: WatchersT
}

export class BamlSyncClient {
  private httpRequest: HttpRequest
  private httpStreamRequest: HttpStreamRequest
  private llmResponseParser: LlmResponseParser
  private llmStreamParser: LlmStreamParser
  private bamlOptions: BamlCallOptions

  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
    this.httpRequest = new HttpRequest(runtime, ctxManager)
    this.httpStreamRequest = new HttpStreamRequest(runtime, ctxManager)
    this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
    this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
    this.bamlOptions = bamlOptions || {}
  }

  withOptions(bamlOptions: BamlCallOptions) {
    return new BamlSyncClient(this.runtime, this.ctxManager, bamlOptions)
  }

  /*
  * @deprecated NOT IMPLEMENTED as streaming must by async. We
  * are not providing an async version as we want to reserve the
  * right to provide a sync version in the future.
  */
  get stream() {
    throw new Error("stream is not available in BamlSyncClient. Use `import { b } from 'baml_client/async_client")
  }

  get request() {
    return this.httpRequest
  }

  get streamRequest() {
    return this.httpStreamRequest
  }

  get parse() {
    return this.llmResponseParser
  }

  get parseStream() {
    return this.llmStreamParser
  }

  
  AuditToolRisk(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ToolRiskAudit {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "AuditToolRisk",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ToolRiskAudit
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ClassifyConversationBoundary(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ConversationBoundary {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ClassifyConversationBoundary",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ConversationBoundary
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  DecideGoalMicroLoop(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.GoalMicroLoopDecision[] {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "DecideGoalMicroLoop",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.GoalMicroLoopDecision[]
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  DecideResidentIdle(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ResidentIdleDecision {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "DecideResidentIdle",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ResidentIdleDecision
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  EvolveTurn(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.DirectDecision | types.AskUserDecision | types.ExecuteDecision {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "EvolveTurn",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.DirectDecision | types.AskUserDecision | types.ExecuteDecision
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityFacts(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ContinuityCapture {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ExtractContinuityFacts",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ContinuityCapture
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityRules(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ContinuityRuleExtractionResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ExtractContinuityRules",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ContinuityRuleExtractionResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  FillPiToolArguments(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.PiToolArgumentsDraft {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "FillPiToolArguments",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.PiToolArgumentsDraft
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  LearnToolUse(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ToolLearningResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "LearnToolUse",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ToolLearningResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ProjectResidentSpeech(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ResidentSpeechProjection {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ProjectResidentSpeech",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ResidentSpeechProjection
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityFacts(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ContinuityCapture {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "RepairContinuityFacts",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ContinuityCapture
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityRules(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ContinuityRuleExtractionResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "RepairContinuityRules",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ContinuityRuleExtractionResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  RepairControllerDecision(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.DirectDecision | types.AskUserDecision | types.ExecuteDecision {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "RepairControllerDecision",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.DirectDecision | types.AskUserDecision | types.ExecuteDecision
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  RepairPiConversationSummary(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.PiConversationSummary {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "RepairPiConversationSummary",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.PiConversationSummary
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  RepairPiToolArguments(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.PiToolArgumentsDraft {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "RepairPiToolArguments",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.PiToolArgumentsDraft
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  RepairToolLearning(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ToolLearningResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "RepairToolLearning",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ToolLearningResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  RepairToolRiskAudit(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ToolRiskAudit {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "RepairToolRiskAudit",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ToolRiskAudit
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SummarizePiConversation(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.PiConversationSummary {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "SummarizePiConversation",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.PiConversationSummary
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SummarizeTemporalMemory(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.TemporalMemoryDigest {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "SummarizeTemporalMemory",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.TemporalMemoryDigest
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlSyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)