/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, Image, Audio, Pdf, Video } from "@boundaryml/baml"
import { toBamlError, HTTPRequest, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type * as types from "./types.js"
import type {ActionPlanInput, ActionRunState, AskUserDecision, AskUserDecisionKind, ContinuityAgendaDraft, ContinuityCapture, ContinuityCaptureItem, ContinuityRuleExtractionResult, ContinuityRuleItem, ConversationBoundary, DirectDecision, DirectDecisionKind, EvidenceSlot, ExecuteDecision, ExecuteDecisionKind, ExecutionDeltaOp, GoalMicroLoopCandidate, GoalMicroLoopDecision, GoalMicroLoopDecisionKind, PiConversationSummary, PiToolArgumentsDraft, PlanFragment, PlannedToolCall, PlannerActiveSkill, PlannerCurrentUserTurn, PlannerEvidenceMemoryItem, PlannerEvidenceRequirement, PlannerEvidenceStateItem, PlannerJournalItem, PlannerTimelineTurn, PlannerToolCallStateItem, ProgressSignals, RepeatedCallWarning, ResidentIdleDecision, ResidentIdleDecisionKind, ResidentIdleGoalProposal, ResidentSpeechProjection, TemporalMemoryDigest, ToolCallArgumentValue, ToolCallStatus, ToolCapabilityFacets, ToolCapabilityItem, ToolCapabilityRisk, ToolCatalogItem, ToolCatalogSummaryItem, ToolEvidenceCapabilityItem, ToolLearningRecord, ToolLearningResult, ToolRiskAudit, ToolRiskAuditDecision, ToolRiskLevel} from "./types.js"
import type TypeBuilder from "./type_builder.js"
import type * as events from "./events.js"

type BamlCallOptions<EventsT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  client?: string
  env?: Record<string, string | undefined>
  events?: EventsT
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AuditToolRisk(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "AuditToolRisk",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ClassifyConversationBoundary(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ClassifyConversationBoundary",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DecideGoalMicroLoop(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "DecideGoalMicroLoop",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DecideResidentIdle(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "DecideResidentIdle",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EvolveTurn(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "EvolveTurn",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityFacts(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractContinuityFacts",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityRules(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractContinuityRules",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  FillPiToolArguments(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "FillPiToolArguments",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  LearnToolUse(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "LearnToolUse",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ProjectResidentSpeech(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ProjectResidentSpeech",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityFacts(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairContinuityFacts",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityRules(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairContinuityRules",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairControllerDecision(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairControllerDecision",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiConversationSummary(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairPiConversationSummary",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiToolArguments(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairPiToolArguments",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolLearning(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairToolLearning",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolRiskAudit(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairToolRiskAudit",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizePiConversation(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "SummarizePiConversation",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeTemporalMemory(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "SummarizeTemporalMemory",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AuditToolRisk(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "AuditToolRisk",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ClassifyConversationBoundary(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ClassifyConversationBoundary",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DecideGoalMicroLoop(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "DecideGoalMicroLoop",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DecideResidentIdle(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "DecideResidentIdle",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EvolveTurn(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "EvolveTurn",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityFacts(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractContinuityFacts",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractContinuityRules(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractContinuityRules",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  FillPiToolArguments(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "FillPiToolArguments",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  LearnToolUse(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "LearnToolUse",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ProjectResidentSpeech(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ProjectResidentSpeech",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityFacts(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairContinuityFacts",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairContinuityRules(
      stablePrompt: string,promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairContinuityRules",
        {
          "stablePrompt": stablePrompt,"promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairControllerDecision(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairControllerDecision",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiConversationSummary(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairPiConversationSummary",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairPiToolArguments(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairPiToolArguments",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolLearning(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairToolLearning",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  RepairToolRiskAudit(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "RepairToolRiskAudit",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizePiConversation(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "SummarizePiConversation",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeTemporalMemory(
      promptJson: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "SummarizeTemporalMemory",
        {
          "promptJson": promptJson
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}