/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum EvidenceVerificationStatus {
  Satisfied = "Satisfied",
  Partial = "Partial",
  Missing = "Missing",
  Blocked = "Blocked",
}

export enum ExecutionDeltaOp {
  AddCall = "AddCall",
  AddEvidence = "AddEvidence",
  AddWarning = "AddWarning",
}

export enum InteractionRunMode {
  DirectResponse = "DirectResponse",
  ToolAgentLoop = "ToolAgentLoop",
  DeliberateTaskLoop = "DeliberateTaskLoop",
}

export enum TaskEvidenceScope {
  CurrentRun = "CurrentRun",
  Memory = "Memory",
  Conversation = "Conversation",
}

export enum ToolCallStatus {
  Success = "Success",
  Failure = "Failure",
  Empty = "Empty",
}

export enum TurnContextMode {
  None = "None",
  Used = "Used",
  Insufficient = "Insufficient",
}

export interface ActionPlanInput {
  currentUserTurn: PlannerCurrentUserTurn
  turnUnderstanding?: TurnUnderstanding | null
  roleplayPreset?: PlannerRoleplayPreset | null
  runState: ActionRunState
  timeline: PlannerTimelineTurn[]
  evidenceMemory: PlannerEvidenceMemoryItem[]
  evidenceState: PlannerEvidenceStateItem[]
  plannerJournal: PlannerJournalItem[]
  plannerState?: PlannerStateSnapshot | null
  toolTagCatalog: string[]
  compactToolCatalog: ToolCatalogSummaryItem[]
  toolCatalog: ToolCatalogItem[]
  activeSkills: PlannerActiveSkill[]
  
}

export interface ActionRunState {
  currentStep: number
  dynamicTools: boolean
  loadedTools: string[]
  progress: ProgressSignals
  warnings: RepeatedCallWarning[]
  calls: PlannerToolCallStateItem[]
  
}

export interface EvidenceRequirementVerification {
  requirementId: string
  need: string
  status: EvidenceVerificationStatus
  evidenceUris: string[]
  artifactUris: string[]
  reason: string
  missingFacts: string[]
  unsupportedClaims: string[]
  
}

export interface EvidenceSlot {
  name: string
  value: string
  
}

export interface EvidenceVerification {
  ready: boolean
  requirements: EvidenceRequirementVerification[]
  summary: string
  
}

export interface FastContextScoutCommand {
  type: string
  pattern?: string | null
  path?: string | null
  include?: string[] | null
  exclude?: string[] | null
  regex?: boolean | null
  caseSensitive?: boolean | null
  startLine?: number | null
  endLine?: number | null
  depth?: number | null
  
}

export interface FastContextScoutFileSelection {
  path: string
  startLine: number
  endLine: number
  reason: string
  
}

export interface FastContextScoutPlannerDecision {
  action: string
  commands: FastContextScoutCommand[]
  files: FastContextScoutFileSelection[]
  reason: string
  
}

export interface InteractionRoute {
  mode: InteractionRunMode
  objective: string
  needsFreshEvidence: boolean
  needsWorkspaceRead: boolean
  needsSideEffect: boolean
  risk: string
  preferredTools: string[]
  discoveryQueries: string[]
  reason: string
  
}

export interface MemoryCandidate {
  type: string
  subject: string
  claim: string
  howToApply: string
  tags: string[]
  triggers: string[]
  sourceRefs: string[]
  reason: string
  confidence: number
  
}

export interface MemoryConsolidationAction {
  operation: string
  type: string
  subject: string
  claim: string
  howToApply: string
  tags: string[]
  triggers: string[]
  sourceRefs: string[]
  candidateUris: string[]
  targetMemoryUri?: string | null
  reason: string
  confidence: number
  
}

export interface MemoryConsolidationResult {
  actions: MemoryConsolidationAction[]
  
}

export interface MemoryLearningResult {
  candidates: MemoryCandidate[]
  
}

export interface MemoryWriteDecision {
  operation: string
  type: string
  subject: string
  claim: string
  howToApply: string
  tags: string[]
  triggers: string[]
  sourceRefs: string[]
  candidateUris: string[]
  targetMemoryUri?: string | null
  reason: string
  confidence: number
  
}

export interface MemoryWriteResolutionResult {
  decision: MemoryWriteDecision
  
}

export interface PlannedToolCall {
  name: string
  arguments: Record<string, ToolCallArgumentValue>
  
}

export interface PlannerActiveSkill {
  name: string
  title: string
  summary: string
  useCases: string[]
  avoid: string[]
  recommendedTools: string[]
  evidenceRequirements: PlannerEvidenceRequirement[]
  
}

export interface PlannerCurrentUserTurn {
  requestId?: string | null
  content: string
  
}

export interface PlannerEvidenceMemoryItem {
  evidenceUri: string
  kind: string
  locator: string
  display: string
  label: string
  toolName: string
  artifactUri: string
  facts: EvidenceSlot[]
  artifactRefs: string[]
  
}

export interface PlannerEvidenceRequirement {
  need: string
  accepts: string[]
  minimumQuality: string[]
  minimum: number
  purpose: string
  
}

export interface PlannerEvidenceStateItem {
  evidenceUri: string
  kind: string
  toolName: string
  artifactUri: string
  locator: string
  display: string
  label: string
  source?: string | null
  confidence?: number | null
  facts: EvidenceSlot[]
  artifactRefs: string[]
  
}

export interface PlannerJournalItem {
  requestId: string
  step: number
  selectedAction: string
  evidenceUris: string[]
  artifactUris: string[]
  loadedTools: string[]
  outcome: string
  
}

export interface PlannerRoleplayPreset {
  enabled: boolean
  activePresetName?: string | null
  documents: PlannerRoleplayPresetDocument[]
  
}

export interface PlannerRoleplayPresetDocument {
  name: string
  format: string
  title: string
  updatedAt: string
  content: string
  
}

export interface PlannerStateCandidateTool {
  name: string
  purpose: string
  supports: string[]
  
}

export interface PlannerStateEffect {
  id: string
  effect: string
  target: string
  reason: string
  
}

export interface PlannerStateEvidence {
  evidenceUri: string
  kind: string
  toolName: string
  artifactUri: string
  locator: string
  display: string
  label: string
  
}

export interface PlannerStateEvidenceNeed {
  id: string
  need: string
  scope: string
  minimum: number
  reason: string
  
}

export interface PlannerStateOpenQuestion {
  question: string
  reason: string
  
}

export interface PlannerStateSnapshot {
  taskId: string
  requestId: string
  step: number
  status: string
  userGoal: string
  currentIntent: string
  intentTags: string[]
  taskTags: string[]
  targetRefs: PlannerStateTargetRef[]
  requiredEffects: PlannerStateEffect[]
  evidenceNeeds: PlannerStateEvidenceNeed[]
  completedEvidence: PlannerStateEvidence[]
  completedEffects: PlannerStateEffect[]
  openQuestions: PlannerStateOpenQuestion[]
  candidateTools: PlannerStateCandidateTool[]
  discoveryQueries: string[]
  nextStepPurpose: string
  completionCriteria: string[]
  lastAction: string
  loadedTools: string[]
  recentCalls: PlannerToolCallStateItem[]
  updatedAt: string
  
}

export interface PlannerStateTargetRef {
  kind: string
  value: string
  status: string
  
}

export interface PlannerTimelineTurn {
  index: number
  role: string
  kind: string
  step?: number | null
  content: string
  payloadJson?: string | null
  evidenceUris: string[]
  artifactUris: string[]
  
}

export interface PlannerToolCallStateItem {
  step: number
  toolName: string
  status: ToolCallStatus
  artifactUri: string
  evidenceUris: string[]
  resultKind: string
  argumentsPreview: string
  error: string
  
}

export interface ProgressSignals {
  totalToolCalls: number
  totalEvidence: number
  lastNewEvidenceStep: number
  repeatedCallCount: number
  stalled: boolean
  
}

export interface RepeatedCallWarning {
  toolName: string
  argsHash: string
  count: number
  lastStep: number
  
}

export interface TaskCandidateTool {
  name: string
  purpose: string
  supports: string[]
  
}

export interface TaskFrame {
  taskType: string
  answerGoal: string
  intentTags: string[]
  taskTags: string[]
  targetRefs: TaskTargetRef[]
  candidateTools: TaskCandidateTool[]
  discoveryQueries: string[]
  requiredEffects: TaskRequiredEffect[]
  requiredEvidence: TaskRequiredEvidence[]
  userInputNeeds: TaskUserInputNeed[]
  nextStepPurpose: string
  completionCriteria: string[]
  notes: string[]
  
}

export interface TaskRequiredEffect {
  id: string
  effect: string
  target: string
  proof: string
  reason: string
  
}

export interface TaskRequiredEvidence {
  id: string
  need: string
  scope: TaskEvidenceScope
  minimum: number
  reason: string
  
}

export interface TaskTargetRef {
  kind: string
  value: string
  status: string
  
}

export interface TaskUserInputNeed {
  question: string
  reason: string
  
}

export interface ToolCallPlan {
  calls: PlannedToolCall[]
  
}

export interface ToolCapabilityFacets {
  Actions?: string[] | null
  Targets?: string[] | null
  Inputs?: string[] | null
  Outputs?: string[] | null
  Evidence?: string[] | null
  Effects?: string[] | null
  
}

export interface ToolCapabilityItem {
  id: string
  title: string
  description: string
  facets: ToolCapabilityFacets
  risk?: ToolCapabilityRisk | null
  
}

export interface ToolCapabilityRisk {
  sideEffect?: string | null
  permission?: string | null
  
}

export interface ToolCatalogItem {
  name: string
  title: string
  summary: string
  capabilities: ToolCapabilityItem[]
  tags: string[]
  useCases: string[]
  examples: string[]
  avoid: string[]
  permissions: string[]
  evidenceCapabilities: ToolEvidenceCapabilityItem[]
  loaded: boolean
  
}

export interface ToolCatalogSummaryItem {
  name: string
  title: string
  summary: string
  capabilities: string[]
  evidence: string[]
  effects: string[]
  outputs: string[]
  permissions: string[]
  loaded: boolean
  rootKind: string
  
}

export interface ToolEvidenceCapabilityItem {
  produces: string
  quality: string
  satisfies: string[]
  kinds: string[]
  capabilityIds: string[]
  
}

export interface ToolLearningRecord {
  toolName: string
  tags: string[]
  sourceTerms: string[]
  triggers: string[]
  reason: string
  confidence: number
  
}

export interface ToolLearningResult {
  records: ToolLearningRecord[]
  
}

export interface TurnUnderstanding {
  rawUserTurn: string
  standaloneRequest: string
  contextMode: TurnContextMode
  contextBasis: string
  missingContext: string
  
}

export interface ToolCallArgumentValue {
  [key: string]: ToolCallArgumentValue
}
