/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum AskUserDecisionKind {
  AskUser = "AskUser",
}

export enum DirectDecisionKind {
  Direct = "Direct",
}

export enum ExecuteDecisionKind {
  Execute = "Execute",
}

export enum ExecutionDeltaOp {
  AddCall = "AddCall",
  AddEvidence = "AddEvidence",
  AddWarning = "AddWarning",
}

export enum GoalMicroLoopDecisionKind {
  Wait = "Wait",
  Propose = "Propose",
  AskUser = "AskUser",
  Execute = "Execute",
  Replan = "Replan",
  Complete = "Complete",
  Block = "Block",
}

export enum ResidentIdleDecisionKind {
  Wait = "Wait",
  Reflect = "Reflect",
  CreateGoal = "CreateGoal",
  Notify = "Notify",
}

export enum ToolCallStatus {
  Success = "Success",
  Failure = "Failure",
  Empty = "Empty",
}

export enum ToolRiskAuditDecision {
  Allow = "Allow",
  Ask = "Ask",
  Deny = "Deny",
}

export enum ToolRiskLevel {
  Low = "Low",
  Medium = "Medium",
  High = "High",
  Critical = "Critical",
}

export interface ActionPlanInput {
  currentUserTurn: PlannerCurrentUserTurn
  runState: ActionRunState
  timeline: PlannerTimelineTurn[]
  evidenceMemory: PlannerEvidenceMemoryItem[]
  evidenceState: PlannerEvidenceStateItem[]
  plannerJournal: PlannerJournalItem[]
  toolTagCatalog: string[]
  compactToolCatalog: ToolCatalogSummaryItem[]
  toolCatalog: ToolCatalogItem[]
  activeSkills: PlannerActiveSkill[]
  
}

export interface ActionRunState {
  currentStep: number
  loadedTools: string[]
  progress: ProgressSignals
  warnings: RepeatedCallWarning[]
  calls: PlannerToolCallStateItem[]
  
}

export interface AskUserDecision {
  kind: AskUserDecisionKind
  question: string
  
}

export interface ContinuityAgendaDraft {
  kind: string
  change: string
  actor: string
  summary: string
  timeText?: string | null
  relatesTo?: string | null
  
}

export interface ContinuityCapture {
  items: ContinuityCaptureItem[]
  agenda: ContinuityAgendaDraft[]
  needsRulePass: boolean
  
}

export interface ContinuityCaptureItem {
  kind: string
  text?: string | null
  key?: string | null
  value?: string | number | boolean | null
  from?: string | null
  relation?: string | null
  to?: string | null
  
}

export interface ContinuityRuleExtractionResult {
  items: ContinuityRuleItem[]
  
}

export interface ContinuityRuleItem {
  kind: string
  title: string
  target?: string | null
  replace?: boolean | null
  value?: string | number | boolean | null
  when?: Record<string, string | number | boolean> | null
  at?: string | null
  match?: string | null
  threshold?: number | null
  effect?: string | null
  until: string
  
}

export interface ConversationBoundary {
  relation: string
  confidence: number
  focus: string
  
}

export interface DirectDecision {
  kind: DirectDecisionKind
  response: string
  
}

export interface EvidenceSlot {
  name: string
  value: string
  
}

export interface ExecuteDecision {
  kind: ExecuteDecisionKind
  fragment: PlanFragment
  
}

export interface GoalMicroLoopCandidate {
  goalId: string
  summary: string
  status: string
  intentMode?: string | null
  priority: number
  progress: number
  successCriteria: string[]
  trigger: string
  triggerKey: string
  sourceRefs: string[]
  dueAt?: string | null
  nextReviewAt?: string | null
  
}

export interface GoalMicroLoopDecision {
  goalId: string
  triggerKey: string
  kind: GoalMicroLoopDecisionKind
  reason: string
  nextReviewAt?: string | null
  progress?: number | null
  blockedReason?: string | null
  
}

export interface PiConversationSummary {
  summary: string
  
}

export interface PiToolArgumentsDraft {
  arguments: Record<string, ToolCallArgumentValue>
  missingInputs: string[]
  assumptions: string[]
  
}

export interface PlanFragment {
  preface: string
  calls: PlannedToolCall[]
  
}

export interface PlannedToolCall {
  toolName: string
  purpose: string
  required: boolean
  dependsOn?: number[] | null
  
}

export interface PlannerActiveSkill {
  name: string
  title: string
  summary: string
  useCases: string[]
  avoid: string[]
  recommendedTools: string[]
  evidenceRequirements: PlannerEvidenceRequirement[]
  
}

export interface PlannerCurrentUserTurn {
  requestId?: string | null
  content: string
  
}

export interface PlannerEvidenceMemoryItem {
  evidenceUri: string
  kind: string
  locator: string
  display: string
  label: string
  toolName: string
  artifactUri: string
  facts: EvidenceSlot[]
  artifactRefs: string[]
  
}

export interface PlannerEvidenceRequirement {
  need: string
  accepts: string[]
  minimumQuality: string[]
  minimum: number
  purpose: string
  
}

export interface PlannerEvidenceStateItem {
  evidenceUri: string
  kind: string
  toolName: string
  artifactUri: string
  locator: string
  display: string
  label: string
  source?: string | null
  confidence?: number | null
  facts: EvidenceSlot[]
  artifactRefs: string[]
  
}

export interface PlannerJournalItem {
  requestId: string
  step: number
  selectedAction: string
  evidenceUris: string[]
  artifactUris: string[]
  loadedTools: string[]
  outcome: string
  
}

export interface PlannerTimelineTurn {
  index: number
  role: string
  kind: string
  step?: number | null
  content: string
  payloadJson?: string | null
  evidenceUris: string[]
  artifactUris: string[]
  
}

export interface PlannerToolCallStateItem {
  step: number
  toolName: string
  status: ToolCallStatus
  artifactUri: string
  evidenceUris: string[]
  resultKind: string
  argumentsPreview: string
  error: string
  failureKind: string
  failureSource: string
  retryable?: boolean | null
  
}

export interface ProgressSignals {
  totalToolCalls: number
  totalEvidence: number
  lastNewEvidenceStep: number
  repeatedCallCount: number
  stalled: boolean
  
}

export interface RepeatedCallWarning {
  toolName: string
  argsHash: string
  count: number
  lastStep: number
  
}

export interface ResidentIdleDecision {
  kind: ResidentIdleDecisionKind
  reason: string
  goal?: ResidentIdleGoalProposal | null
  message?: string | null
  
}

export interface ResidentIdleGoalProposal {
  summary: string
  detail?: string | null
  priority?: number | null
  successCriteria?: string[] | null
  
}

export interface ResidentSpeechProjection {
  utterance: string
  
}

export interface TemporalMemoryDigest {
  summary: string
  topics: string[]
  openLoops: string[]
  
}

export interface ToolCapabilityFacets {
  Actions?: string[] | null
  Targets?: string[] | null
  Inputs?: string[] | null
  Outputs?: string[] | null
  Evidence?: string[] | null
  Effects?: string[] | null
  
}

export interface ToolCapabilityItem {
  id: string
  title: string
  description: string
  facets: ToolCapabilityFacets
  risk?: ToolCapabilityRisk | null
  
}

export interface ToolCapabilityRisk {
  sideEffect?: string | null
  permission?: string | null
  
}

export interface ToolCatalogItem {
  name: string
  title: string
  summary: string
  capabilities: ToolCapabilityItem[]
  tags: string[]
  useCases: string[]
  examples: string[]
  avoid: string[]
  permissions: string[]
  evidenceCapabilities: ToolEvidenceCapabilityItem[]
  loaded: boolean
  
}

export interface ToolCatalogSummaryItem {
  name: string
  title: string
  summary: string
  capabilities: string[]
  evidence: string[]
  effects: string[]
  outputs: string[]
  permissions: string[]
  loaded: boolean
  rootKind: string
  
}

export interface ToolEvidenceCapabilityItem {
  produces: string
  quality: string
  satisfies: string[]
  kinds: string[]
  capabilityIds: string[]
  
}

export interface ToolLearningRecord {
  toolName: string
  tags: string[]
  sourceTerms: string[]
  triggers: string[]
  reason: string
  confidence: number
  
}

export interface ToolLearningResult {
  records: ToolLearningRecord[]
  
}

export interface ToolRiskAudit {
  decision: ToolRiskAuditDecision
  riskLevel: ToolRiskLevel
  confidence: number
  tripwire: boolean
  reason: string
  matchedConcerns: string[]
  safeAlternative?: string | null
  
}

export type ContinuityScalar = string | number | boolean

export type ControllerDecision = DirectDecision | AskUserDecision | ExecuteDecision

export interface ToolCallArgumentValue {
  [key: string]: ToolCallArgumentValue
}
