/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    ActionPlanInput: ClassViewer<'ActionPlanInput', "currentUserTurn" | "turnUnderstanding" | "roleplayPreset" | "runState" | "timeline" | "evidenceMemory" | "evidenceState" | "plannerJournal" | "plannerState" | "toolTagCatalog" | "compactToolCatalog" | "toolCatalog" | "activeSkills">;
    
    ActionRunState: ClassViewer<'ActionRunState', "currentStep" | "dynamicTools" | "loadedTools" | "progress" | "warnings" | "calls">;
    
    EvidenceRequirementVerification: ClassViewer<'EvidenceRequirementVerification', "requirementId" | "need" | "status" | "evidenceUris" | "artifactUris" | "reason" | "missingFacts" | "unsupportedClaims">;
    
    EvidenceSlot: ClassViewer<'EvidenceSlot', "name" | "value">;
    
    EvidenceVerification: ClassViewer<'EvidenceVerification', "ready" | "requirements" | "summary">;
    
    FastContextScoutCommand: ClassViewer<'FastContextScoutCommand', "type" | "pattern" | "path" | "include" | "exclude" | "regex" | "caseSensitive" | "startLine" | "endLine" | "depth">;
    
    FastContextScoutFileSelection: ClassViewer<'FastContextScoutFileSelection', "path" | "startLine" | "endLine" | "reason">;
    
    FastContextScoutPlannerDecision: ClassViewer<'FastContextScoutPlannerDecision', "action" | "commands" | "files" | "reason">;
    
    InteractionRoute: ClassViewer<'InteractionRoute', "mode" | "objective" | "needsFreshEvidence" | "needsWorkspaceRead" | "needsSideEffect" | "risk" | "preferredTools" | "discoveryQueries" | "reason">;
    
    MemoryCandidate: ClassViewer<'MemoryCandidate', "type" | "subject" | "claim" | "howToApply" | "tags" | "triggers" | "sourceRefs" | "reason" | "confidence">;
    
    MemoryConsolidationAction: ClassViewer<'MemoryConsolidationAction', "operation" | "type" | "subject" | "claim" | "howToApply" | "tags" | "triggers" | "sourceRefs" | "candidateUris" | "targetMemoryUri" | "reason" | "confidence">;
    
    MemoryConsolidationResult: ClassViewer<'MemoryConsolidationResult', "actions">;
    
    MemoryLearningResult: ClassViewer<'MemoryLearningResult', "candidates">;
    
    MemoryWriteDecision: ClassViewer<'MemoryWriteDecision', "operation" | "type" | "subject" | "claim" | "howToApply" | "tags" | "triggers" | "sourceRefs" | "candidateUris" | "targetMemoryUri" | "reason" | "confidence">;
    
    MemoryWriteResolutionResult: ClassViewer<'MemoryWriteResolutionResult', "decision">;
    
    PlannedToolCall: ClassViewer<'PlannedToolCall', "name" | "arguments">;
    
    PlannerActiveSkill: ClassViewer<'PlannerActiveSkill', "name" | "title" | "summary" | "useCases" | "avoid" | "recommendedTools" | "evidenceRequirements">;
    
    PlannerCurrentUserTurn: ClassViewer<'PlannerCurrentUserTurn', "requestId" | "content">;
    
    PlannerEvidenceMemoryItem: ClassViewer<'PlannerEvidenceMemoryItem', "evidenceUri" | "kind" | "locator" | "display" | "label" | "toolName" | "artifactUri" | "facts" | "artifactRefs">;
    
    PlannerEvidenceRequirement: ClassViewer<'PlannerEvidenceRequirement', "need" | "accepts" | "minimumQuality" | "minimum" | "purpose">;
    
    PlannerEvidenceStateItem: ClassViewer<'PlannerEvidenceStateItem', "evidenceUri" | "kind" | "toolName" | "artifactUri" | "locator" | "display" | "label" | "source" | "confidence" | "facts" | "artifactRefs">;
    
    PlannerJournalItem: ClassViewer<'PlannerJournalItem', "requestId" | "step" | "selectedAction" | "evidenceUris" | "artifactUris" | "loadedTools" | "outcome">;
    
    PlannerRoleplayPreset: ClassViewer<'PlannerRoleplayPreset', "enabled" | "activePresetName" | "documents">;
    
    PlannerRoleplayPresetDocument: ClassViewer<'PlannerRoleplayPresetDocument', "name" | "format" | "title" | "updatedAt" | "content">;
    
    PlannerStateCandidateTool: ClassViewer<'PlannerStateCandidateTool', "name" | "purpose" | "supports">;
    
    PlannerStateEffect: ClassViewer<'PlannerStateEffect', "id" | "effect" | "target" | "reason">;
    
    PlannerStateEvidence: ClassViewer<'PlannerStateEvidence', "evidenceUri" | "kind" | "toolName" | "artifactUri" | "locator" | "display" | "label">;
    
    PlannerStateEvidenceNeed: ClassViewer<'PlannerStateEvidenceNeed', "id" | "need" | "scope" | "minimum" | "reason">;
    
    PlannerStateOpenQuestion: ClassViewer<'PlannerStateOpenQuestion', "question" | "reason">;
    
    PlannerStateSnapshot: ClassViewer<'PlannerStateSnapshot', "taskId" | "requestId" | "step" | "status" | "userGoal" | "currentIntent" | "intentTags" | "taskTags" | "targetRefs" | "requiredEffects" | "evidenceNeeds" | "completedEvidence" | "completedEffects" | "openQuestions" | "candidateTools" | "discoveryQueries" | "nextStepPurpose" | "completionCriteria" | "lastAction" | "loadedTools" | "recentCalls" | "updatedAt">;
    
    PlannerStateTargetRef: ClassViewer<'PlannerStateTargetRef', "kind" | "value" | "status">;
    
    PlannerTimelineTurn: ClassViewer<'PlannerTimelineTurn', "index" | "role" | "kind" | "step" | "content" | "payloadJson" | "evidenceUris" | "artifactUris">;
    
    PlannerToolCallStateItem: ClassViewer<'PlannerToolCallStateItem', "step" | "toolName" | "status" | "artifactUri" | "evidenceUris" | "resultKind" | "argumentsPreview" | "error">;
    
    ProgressSignals: ClassViewer<'ProgressSignals', "totalToolCalls" | "totalEvidence" | "lastNewEvidenceStep" | "repeatedCallCount" | "stalled">;
    
    RepeatedCallWarning: ClassViewer<'RepeatedCallWarning', "toolName" | "argsHash" | "count" | "lastStep">;
    
    TaskCandidateTool: ClassViewer<'TaskCandidateTool', "name" | "purpose" | "supports">;
    
    TaskFrame: ClassViewer<'TaskFrame', "taskType" | "answerGoal" | "intentTags" | "taskTags" | "targetRefs" | "candidateTools" | "discoveryQueries" | "requiredEffects" | "requiredEvidence" | "userInputNeeds" | "nextStepPurpose" | "completionCriteria" | "notes">;
    
    TaskRequiredEffect: ClassViewer<'TaskRequiredEffect', "id" | "effect" | "target" | "proof" | "reason">;
    
    TaskRequiredEvidence: ClassViewer<'TaskRequiredEvidence', "id" | "need" | "scope" | "minimum" | "reason">;
    
    TaskTargetRef: ClassViewer<'TaskTargetRef', "kind" | "value" | "status">;
    
    TaskUserInputNeed: ClassViewer<'TaskUserInputNeed', "question" | "reason">;
    
    ToolCallPlan: ClassViewer<'ToolCallPlan', "calls">;
    
    ToolCapabilityFacets: ClassViewer<'ToolCapabilityFacets', "Actions" | "Targets" | "Inputs" | "Outputs" | "Evidence" | "Effects">;
    
    ToolCapabilityItem: ClassViewer<'ToolCapabilityItem', "id" | "title" | "description" | "facets" | "risk">;
    
    ToolCapabilityRisk: ClassViewer<'ToolCapabilityRisk', "sideEffect" | "permission">;
    
    ToolCatalogItem: ClassViewer<'ToolCatalogItem', "name" | "title" | "summary" | "capabilities" | "tags" | "useCases" | "examples" | "avoid" | "permissions" | "evidenceCapabilities" | "loaded">;
    
    ToolCatalogSummaryItem: ClassViewer<'ToolCatalogSummaryItem', "name" | "title" | "summary" | "capabilities" | "evidence" | "effects" | "outputs" | "permissions" | "loaded" | "rootKind">;
    
    ToolEvidenceCapabilityItem: ClassViewer<'ToolEvidenceCapabilityItem', "produces" | "quality" | "satisfies" | "kinds" | "capabilityIds">;
    
    ToolLearningRecord: ClassViewer<'ToolLearningRecord', "toolName" | "tags" | "sourceTerms" | "triggers" | "reason" | "confidence">;
    
    ToolLearningResult: ClassViewer<'ToolLearningResult', "records">;
    
    TurnUnderstanding: ClassViewer<'TurnUnderstanding', "rawUserTurn" | "standaloneRequest" | "contextMode" | "contextBasis" | "missingContext">;
    
    
    EvidenceVerificationStatus: EnumViewer<'EvidenceVerificationStatus', "Satisfied" | "Partial" | "Missing" | "Blocked">;
    
    ExecutionDeltaOp: EnumViewer<'ExecutionDeltaOp', "AddCall" | "AddEvidence" | "AddWarning">;
    
    InteractionRunMode: EnumViewer<'InteractionRunMode', "DirectResponse" | "ToolAgentLoop" | "DeliberateTaskLoop">;
    
    TaskEvidenceScope: EnumViewer<'TaskEvidenceScope', "CurrentRun" | "Memory" | "Conversation">;
    
    ToolCallStatus: EnumViewer<'ToolCallStatus', "Success" | "Failure" | "Empty">;
    
    TurnContextMode: EnumViewer<'TurnContextMode', "None" | "Used" | "Insufficient">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "ActionPlanInput","ActionRunState","EvidenceRequirementVerification","EvidenceSlot","EvidenceVerification","FastContextScoutCommand","FastContextScoutFileSelection","FastContextScoutPlannerDecision","InteractionRoute","MemoryCandidate","MemoryConsolidationAction","MemoryConsolidationResult","MemoryLearningResult","MemoryWriteDecision","MemoryWriteResolutionResult","PlannedToolCall","PlannerActiveSkill","PlannerCurrentUserTurn","PlannerEvidenceMemoryItem","PlannerEvidenceRequirement","PlannerEvidenceStateItem","PlannerJournalItem","PlannerRoleplayPreset","PlannerRoleplayPresetDocument","PlannerStateCandidateTool","PlannerStateEffect","PlannerStateEvidence","PlannerStateEvidenceNeed","PlannerStateOpenQuestion","PlannerStateSnapshot","PlannerStateTargetRef","PlannerTimelineTurn","PlannerToolCallStateItem","ProgressSignals","RepeatedCallWarning","TaskCandidateTool","TaskFrame","TaskRequiredEffect","TaskRequiredEvidence","TaskTargetRef","TaskUserInputNeed","ToolCallPlan","ToolCapabilityFacets","ToolCapabilityItem","ToolCapabilityRisk","ToolCatalogItem","ToolCatalogSummaryItem","ToolEvidenceCapabilityItem","ToolLearningRecord","ToolLearningResult","TurnUnderstanding",
          ]),
          enums: new Set([
            "EvidenceVerificationStatus","ExecutionDeltaOp","InteractionRunMode","TaskEvidenceScope","ToolCallStatus","TurnContextMode",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.ActionPlanInput = this.tb.classViewer("ActionPlanInput", [
          "currentUserTurn","turnUnderstanding","roleplayPreset","runState","timeline","evidenceMemory","evidenceState","plannerJournal","plannerState","toolTagCatalog","compactToolCatalog","toolCatalog","activeSkills",
        ]);
        
        this.ActionRunState = this.tb.classViewer("ActionRunState", [
          "currentStep","dynamicTools","loadedTools","progress","warnings","calls",
        ]);
        
        this.EvidenceRequirementVerification = this.tb.classViewer("EvidenceRequirementVerification", [
          "requirementId","need","status","evidenceUris","artifactUris","reason","missingFacts","unsupportedClaims",
        ]);
        
        this.EvidenceSlot = this.tb.classViewer("EvidenceSlot", [
          "name","value",
        ]);
        
        this.EvidenceVerification = this.tb.classViewer("EvidenceVerification", [
          "ready","requirements","summary",
        ]);
        
        this.FastContextScoutCommand = this.tb.classViewer("FastContextScoutCommand", [
          "type","pattern","path","include","exclude","regex","caseSensitive","startLine","endLine","depth",
        ]);
        
        this.FastContextScoutFileSelection = this.tb.classViewer("FastContextScoutFileSelection", [
          "path","startLine","endLine","reason",
        ]);
        
        this.FastContextScoutPlannerDecision = this.tb.classViewer("FastContextScoutPlannerDecision", [
          "action","commands","files","reason",
        ]);
        
        this.InteractionRoute = this.tb.classViewer("InteractionRoute", [
          "mode","objective","needsFreshEvidence","needsWorkspaceRead","needsSideEffect","risk","preferredTools","discoveryQueries","reason",
        ]);
        
        this.MemoryCandidate = this.tb.classViewer("MemoryCandidate", [
          "type","subject","claim","howToApply","tags","triggers","sourceRefs","reason","confidence",
        ]);
        
        this.MemoryConsolidationAction = this.tb.classViewer("MemoryConsolidationAction", [
          "operation","type","subject","claim","howToApply","tags","triggers","sourceRefs","candidateUris","targetMemoryUri","reason","confidence",
        ]);
        
        this.MemoryConsolidationResult = this.tb.classViewer("MemoryConsolidationResult", [
          "actions",
        ]);
        
        this.MemoryLearningResult = this.tb.classViewer("MemoryLearningResult", [
          "candidates",
        ]);
        
        this.MemoryWriteDecision = this.tb.classViewer("MemoryWriteDecision", [
          "operation","type","subject","claim","howToApply","tags","triggers","sourceRefs","candidateUris","targetMemoryUri","reason","confidence",
        ]);
        
        this.MemoryWriteResolutionResult = this.tb.classViewer("MemoryWriteResolutionResult", [
          "decision",
        ]);
        
        this.PlannedToolCall = this.tb.classViewer("PlannedToolCall", [
          "name","arguments",
        ]);
        
        this.PlannerActiveSkill = this.tb.classViewer("PlannerActiveSkill", [
          "name","title","summary","useCases","avoid","recommendedTools","evidenceRequirements",
        ]);
        
        this.PlannerCurrentUserTurn = this.tb.classViewer("PlannerCurrentUserTurn", [
          "requestId","content",
        ]);
        
        this.PlannerEvidenceMemoryItem = this.tb.classViewer("PlannerEvidenceMemoryItem", [
          "evidenceUri","kind","locator","display","label","toolName","artifactUri","facts","artifactRefs",
        ]);
        
        this.PlannerEvidenceRequirement = this.tb.classViewer("PlannerEvidenceRequirement", [
          "need","accepts","minimumQuality","minimum","purpose",
        ]);
        
        this.PlannerEvidenceStateItem = this.tb.classViewer("PlannerEvidenceStateItem", [
          "evidenceUri","kind","toolName","artifactUri","locator","display","label","source","confidence","facts","artifactRefs",
        ]);
        
        this.PlannerJournalItem = this.tb.classViewer("PlannerJournalItem", [
          "requestId","step","selectedAction","evidenceUris","artifactUris","loadedTools","outcome",
        ]);
        
        this.PlannerRoleplayPreset = this.tb.classViewer("PlannerRoleplayPreset", [
          "enabled","activePresetName","documents",
        ]);
        
        this.PlannerRoleplayPresetDocument = this.tb.classViewer("PlannerRoleplayPresetDocument", [
          "name","format","title","updatedAt","content",
        ]);
        
        this.PlannerStateCandidateTool = this.tb.classViewer("PlannerStateCandidateTool", [
          "name","purpose","supports",
        ]);
        
        this.PlannerStateEffect = this.tb.classViewer("PlannerStateEffect", [
          "id","effect","target","reason",
        ]);
        
        this.PlannerStateEvidence = this.tb.classViewer("PlannerStateEvidence", [
          "evidenceUri","kind","toolName","artifactUri","locator","display","label",
        ]);
        
        this.PlannerStateEvidenceNeed = this.tb.classViewer("PlannerStateEvidenceNeed", [
          "id","need","scope","minimum","reason",
        ]);
        
        this.PlannerStateOpenQuestion = this.tb.classViewer("PlannerStateOpenQuestion", [
          "question","reason",
        ]);
        
        this.PlannerStateSnapshot = this.tb.classViewer("PlannerStateSnapshot", [
          "taskId","requestId","step","status","userGoal","currentIntent","intentTags","taskTags","targetRefs","requiredEffects","evidenceNeeds","completedEvidence","completedEffects","openQuestions","candidateTools","discoveryQueries","nextStepPurpose","completionCriteria","lastAction","loadedTools","recentCalls","updatedAt",
        ]);
        
        this.PlannerStateTargetRef = this.tb.classViewer("PlannerStateTargetRef", [
          "kind","value","status",
        ]);
        
        this.PlannerTimelineTurn = this.tb.classViewer("PlannerTimelineTurn", [
          "index","role","kind","step","content","payloadJson","evidenceUris","artifactUris",
        ]);
        
        this.PlannerToolCallStateItem = this.tb.classViewer("PlannerToolCallStateItem", [
          "step","toolName","status","artifactUri","evidenceUris","resultKind","argumentsPreview","error",
        ]);
        
        this.ProgressSignals = this.tb.classViewer("ProgressSignals", [
          "totalToolCalls","totalEvidence","lastNewEvidenceStep","repeatedCallCount","stalled",
        ]);
        
        this.RepeatedCallWarning = this.tb.classViewer("RepeatedCallWarning", [
          "toolName","argsHash","count","lastStep",
        ]);
        
        this.TaskCandidateTool = this.tb.classViewer("TaskCandidateTool", [
          "name","purpose","supports",
        ]);
        
        this.TaskFrame = this.tb.classViewer("TaskFrame", [
          "taskType","answerGoal","intentTags","taskTags","targetRefs","candidateTools","discoveryQueries","requiredEffects","requiredEvidence","userInputNeeds","nextStepPurpose","completionCriteria","notes",
        ]);
        
        this.TaskRequiredEffect = this.tb.classViewer("TaskRequiredEffect", [
          "id","effect","target","proof","reason",
        ]);
        
        this.TaskRequiredEvidence = this.tb.classViewer("TaskRequiredEvidence", [
          "id","need","scope","minimum","reason",
        ]);
        
        this.TaskTargetRef = this.tb.classViewer("TaskTargetRef", [
          "kind","value","status",
        ]);
        
        this.TaskUserInputNeed = this.tb.classViewer("TaskUserInputNeed", [
          "question","reason",
        ]);
        
        this.ToolCallPlan = this.tb.classViewer("ToolCallPlan", [
          "calls",
        ]);
        
        this.ToolCapabilityFacets = this.tb.classViewer("ToolCapabilityFacets", [
          "Actions","Targets","Inputs","Outputs","Evidence","Effects",
        ]);
        
        this.ToolCapabilityItem = this.tb.classViewer("ToolCapabilityItem", [
          "id","title","description","facets","risk",
        ]);
        
        this.ToolCapabilityRisk = this.tb.classViewer("ToolCapabilityRisk", [
          "sideEffect","permission",
        ]);
        
        this.ToolCatalogItem = this.tb.classViewer("ToolCatalogItem", [
          "name","title","summary","capabilities","tags","useCases","examples","avoid","permissions","evidenceCapabilities","loaded",
        ]);
        
        this.ToolCatalogSummaryItem = this.tb.classViewer("ToolCatalogSummaryItem", [
          "name","title","summary","capabilities","evidence","effects","outputs","permissions","loaded","rootKind",
        ]);
        
        this.ToolEvidenceCapabilityItem = this.tb.classViewer("ToolEvidenceCapabilityItem", [
          "produces","quality","satisfies","kinds","capabilityIds",
        ]);
        
        this.ToolLearningRecord = this.tb.classViewer("ToolLearningRecord", [
          "toolName","tags","sourceTerms","triggers","reason","confidence",
        ]);
        
        this.ToolLearningResult = this.tb.classViewer("ToolLearningResult", [
          "records",
        ]);
        
        this.TurnUnderstanding = this.tb.classViewer("TurnUnderstanding", [
          "rawUserTurn","standaloneRequest","contextMode","contextBasis","missingContext",
        ]);
        
        
        this.EvidenceVerificationStatus = this.tb.enumViewer("EvidenceVerificationStatus", [
          "Satisfied","Partial","Missing","Blocked",
        ]);
        
        this.ExecutionDeltaOp = this.tb.enumViewer("ExecutionDeltaOp", [
          "AddCall","AddEvidence","AddWarning",
        ]);
        
        this.InteractionRunMode = this.tb.enumViewer("InteractionRunMode", [
          "DirectResponse","ToolAgentLoop","DeliberateTaskLoop",
        ]);
        
        this.TaskEvidenceScope = this.tb.enumViewer("TaskEvidenceScope", [
          "CurrentRun","Memory","Conversation",
        ]);
        
        this.ToolCallStatus = this.tb.enumViewer("ToolCallStatus", [
          "Success","Failure","Empty",
        ]);
        
        this.TurnContextMode = this.tb.enumViewer("TurnContextMode", [
          "None","Used","Insufficient",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}