/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum ActionKind {
  Answer = "Answer",
  AskUser = "AskUser",
  DiscoverTools = "DiscoverTools",
  UseTools = "UseTools",
}

export enum ExecutionDeltaOp {
  AddCall = "AddCall",
  AddEvidence = "AddEvidence",
  AddWarning = "AddWarning",
}

export enum ToolCallStatus {
  Success = "Success",
  Failure = "Failure",
  Empty = "Empty",
}

export interface ActionDecision {
  action: ActionKind
  intent: string
  progressAssessment: string
  nextStepGoal: string
  requiredCapabilities: string[]
  tags: string[]
  toolSearchQueries: string[]
  preferredTools: string[]
  confidence: number
  instructionToMainModel: string

}

export interface ActionPlanInput {
  task: ActionTask
  runtime: ActionRuntime
  history: PlannerHistoryTurn[]
  executionState: ExecutionState
  recentDeltas: ExecutionDelta[]
  toolCatalog: ToolCatalogItem[]

}

export interface ActionRuntime {
  currentStep: number
  dynamicTools: boolean
  loadedTools: string[]

}

export interface ActionTask {
  userMessage: string

}

export interface EvidenceRecord {
  key: string
  kind: string
  label: string
  artifactId: string
  source: string

}

export interface ExecutionDelta {
  step: number
  op: ExecutionDeltaOp
  key: string
  toolName: string
  argsHash: string
  status: ToolCallStatus
  artifactId: string
  evidenceKeys: string[]
  note: string

}

export interface ExecutionState {
  calls: ToolCallRecord[]
  evidence: EvidenceRecord[]
  warnings: RepeatedCallWarning[]
  progress: ProgressSignals

}

export interface PlannerHistoryTurn {
  index: number
  role: string
  kind: string
  content: string

}

export interface ProgressSignals {
  totalToolCalls: number
  totalEvidence: number
  lastNewEvidenceStep: number
  repeatedCallCount: number
  stalled: boolean

}

export interface RepeatedCallWarning {
  toolName: string
  argsHash: string
  count: number
  lastStep: number

}

export interface ToolCallRecord {
  step: number
  toolName: string
  argsHash: string
  status: ToolCallStatus
  artifactId: string
  evidenceKeys: string[]
  error: string

}

export interface ToolCatalogItem {
  name: string
  title: string
  summary: string
  tags: string[]
  useCases: string[]
  examples: string[]
  avoid: string[]
  permissions: string[]
  loaded: boolean

}
