// Generated from backend event and transport protocol contracts.
// Run `npm run generate.frontend-events` after editing those contracts.

export const EventLayers = {
  Progress: "progress",
  Snapshot: "snapshot",
  Terminal: "terminal",
  Error: "error",
} as const;
export type EventLayer = (typeof EventLayers)[keyof typeof EventLayers];

export const EventPhases = {
  Request: "request",
  Session: "session",
  Prompt: "prompt",
  Model: "model",
  Decision: "decision",
  Tool: "tool",
  Run: "run",
  Approval: "approval",
  Sandbox: "sandbox",
  Config: "config",
  Orchestration: "orchestration",
} as const;
export type EventPhase = (typeof EventPhases)[keyof typeof EventPhases];

export const EventKinds = {
  SessionCreated: "session.created",
  SessionSnapshot: "session.snapshot",
  SessionClosed: "session.closed",
  SessionBusy: "session.busy",
  SessionNotFound: "session.not_found",
  SessionListSnapshot: "session.list.snapshot",
  SessionHistoryStarted: "session.history.started",
  SessionHistoryChunk: "session.history.chunk",
  SessionHistorySteps: "session.history.steps",
  SessionRunHistoryChunk: "session.run_history.chunk",
  SessionHistoryCompleted: "session.history.completed",
  SessionTruncated: "session.truncated",
  SessionForked: "session.forked",
  SessionCompacted: "session.compacted",
  SessionRuntimeStatus: "session.runtime_status",
  SessionExported: "session.exported",
  RunStarted: "run.started",
  RunActivityChanged: "run.activity.changed",
  RunCancellationProgress: "run.cancellation.progress",
  PromptSummary: "prompt.summary",
  PromptHarnessComposed: "prompt.harness.composed",
  ContinuitySnapshot: "continuity.snapshot",
  ContinuityRulesSnapshot: "continuity.rules.snapshot",
  ContinuityRecallSettled: "continuity.recall.settled",
  ContinuityRecallQuery: "continuity.recall.query",
  AgendaSnapshot: "agenda.snapshot",
  WorldSnapshot: "world.snapshot",
  TodoListWritten: "todo.list.written",
  ExecutionCreated: "execution.created",
  ExecutionStepStarted: "execution.step.started",
  ExecutionStepCompleted: "execution.step.completed",
  ExecutionBlocked: "execution.blocked",
  ExecutionCompleted: "execution.completed",
  ModelStarted: "model.started",
  ModelDelta: "model.delta",
  ModelCompleted: "model.completed",
  ToolCallsPlanned: "tool.calls.planned",
  ToolCallStarted: "tool.call.started",
  ToolCallOutput: "tool.call.output",
  ToolCallProgress: "tool.call.progress",
  ToolCallCompleted: "tool.call.completed",
  ToolCallFailed: "tool.call.failed",
  ToolCallResultDetail: "tool.call.result.detail",
  AssistantMessageCreated: "assistant.message.created",
  ApprovalRequested: "approval.requested",
  ApprovalResolved: "approval.resolved",
  InteractionInputRequested: "interaction.input.requested",
  InteractionInputResolved: "interaction.input.resolved",
  ExecutionResourceCreated: "execution.resource.created",
  ExecutionResourceOutput: "execution.resource.output",
  ExecutionResourceResized: "execution.resource.resized",
  ExecutionResourceState: "execution.resource.state",
  ExecutionResourceRemoved: "execution.resource.removed",
  ExecutionResourceSnapshot: "execution.resource.snapshot",
  SandboxStatusSnapshot: "sandbox.status.snapshot",
  RunCompleted: "run.completed",
  RunFailed: "run.failed",
  RunCancelled: "run.cancelled",
  ChildRunQueued: "child_run.queued",
  ChildRunStarted: "child_run.started",
  ChildRunAwaitingSupervisor: "child_run.awaiting_supervisor",
  ChildRunResumed: "child_run.resumed",
  ChildRunMessageCreated: "child_run.message.created",
  ChildRunSnapshotUpdated: "child_run.snapshot.updated",
  ChildRunDeadlineExtended: "child_run.deadline.extended",
  ChildRunWrappingUp: "child_run.wrapping_up",
  ChildRunCancelling: "child_run.cancelling",
  ChildRunCompleted: "child_run.completed",
  ChildRunPartialCompleted: "child_run.partial_completed",
  ChildRunInterrupted: "child_run.interrupted",
  ChildRunTimedOut: "child_run.timed_out",
  ChildRunFailed: "child_run.failed",
  ChildRunCancelled: "child_run.cancelled",
  WorkflowStarted: "workflow.started",
  WorkflowSnapshotUpdated: "workflow.snapshot.updated",
  WorkflowPaused: "workflow.paused",
  WorkflowCancelling: "workflow.cancelling",
  WorkflowCompleted: "workflow.completed",
  WorkflowPartialCompleted: "workflow.partial_completed",
  WorkflowFailed: "workflow.failed",
  WorkflowCancelled: "workflow.cancelled",
  ScheduledTaskChanged: "scheduled_task.changed",
  ScheduledTaskRunStarted: "scheduled_task.run.started",
  ScheduledTaskRunCompleted: "scheduled_task.run.completed",
  ScheduledTaskRunFailed: "scheduled_task.run.failed",
  SchedulerStatusSnapshot: "scheduler.status.snapshot",
  RequestInvalid: "request.invalid",
  ConfigReloaded: "config.reloaded",
  ConfigFailed: "config.failed",
  ConfigSnapshot: "config.snapshot",
  ModelListSnapshot: "model.list.snapshot",
  ProviderModelsSnapshot: "provider.models.snapshot",
  ProviderModelsFailed: "provider.models.failed",
  ProfileSnapshot: "profile.snapshot",
  PresetSnapshot: "preset.snapshot",
  PresetFailed: "preset.failed",
  SystemToolSnapshot: "system_tool.snapshot",
  McpServerSnapshot: "mcp_server.snapshot",
  ChannelStatusSnapshot: "channel.status.snapshot",
} as const;
export type EventKind = (typeof EventKinds)[keyof typeof EventKinds];

export const EventChannels = {
  AgentEvent: "agent.event",
} as const;
export type EventChannel = (typeof EventChannels)[keyof typeof EventChannels];

export const EventTransportSpecs = {
  "session.created": { layer: "snapshot", phase: "session" },
  "session.snapshot": { layer: "snapshot", phase: "session" },
  "session.closed": { layer: "terminal", phase: "session" },
  "session.busy": { layer: "error", phase: "session" },
  "session.not_found": { layer: "error", phase: "session" },
  "session.list.snapshot": { layer: "snapshot", phase: "session" },
  "session.history.started": { layer: "snapshot", phase: "session" },
  "session.history.chunk": { layer: "snapshot", phase: "session" },
  "session.history.steps": { layer: "snapshot", phase: "session" },
  "session.run_history.chunk": { layer: "snapshot", phase: "session" },
  "session.history.completed": { layer: "snapshot", phase: "session" },
  "session.truncated": { layer: "snapshot", phase: "session" },
  "session.forked": { layer: "snapshot", phase: "session" },
  "session.compacted": { layer: "snapshot", phase: "session" },
  "session.runtime_status": { layer: "snapshot", phase: "session" },
  "session.exported": { layer: "snapshot", phase: "session" },
  "run.started": { layer: "progress", phase: "run" },
  "run.activity.changed": { layer: "progress", phase: "run" },
  "run.cancellation.progress": { layer: "progress", phase: "run" },
  "prompt.summary": { layer: "progress", phase: "prompt" },
  "prompt.harness.composed": { layer: "progress", phase: "prompt" },
  "continuity.snapshot": { layer: "snapshot", phase: "prompt" },
  "continuity.rules.snapshot": { layer: "snapshot", phase: "prompt" },
  "continuity.recall.settled": { layer: "progress", phase: "prompt" },
  "continuity.recall.query": { layer: "progress", phase: "prompt" },
  "agenda.snapshot": { layer: "snapshot", phase: "prompt" },
  "world.snapshot": { layer: "snapshot", phase: "prompt" },
  "todo.list.written": { layer: "snapshot", phase: "tool" },
  "execution.created": { layer: "snapshot", phase: "run" },
  "execution.step.started": { layer: "progress", phase: "run" },
  "execution.step.completed": { layer: "snapshot", phase: "run" },
  "execution.blocked": { layer: "error", phase: "run" },
  "execution.completed": { layer: "terminal", phase: "run" },
  "model.started": { layer: "progress", phase: "model" },
  "model.delta": { layer: "progress", phase: "model" },
  "model.completed": { layer: "snapshot", phase: "model" },
  "tool.calls.planned": { layer: "progress", phase: "tool" },
  "tool.call.started": { layer: "progress", phase: "tool" },
  "tool.call.output": { layer: "progress", phase: "tool" },
  "tool.call.progress": { layer: "progress", phase: "tool" },
  "tool.call.completed": { layer: "progress", phase: "tool" },
  "tool.call.failed": { layer: "error", phase: "tool" },
  "tool.call.result.detail": { layer: "snapshot", phase: "tool" },
  "assistant.message.created": { layer: "progress", phase: "model" },
  "approval.requested": { layer: "progress", phase: "approval" },
  "approval.resolved": { layer: "progress", phase: "approval" },
  "interaction.input.requested": { layer: "progress", phase: "tool" },
  "interaction.input.resolved": { layer: "progress", phase: "tool" },
  "execution.resource.created": { layer: "snapshot", phase: "tool" },
  "execution.resource.output": { layer: "progress", phase: "tool" },
  "execution.resource.state": { layer: "snapshot", phase: "tool" },
  "execution.resource.resized": { layer: "snapshot", phase: "tool" },
  "execution.resource.removed": { layer: "snapshot", phase: "tool" },
  "execution.resource.snapshot": { layer: "snapshot", phase: "tool" },
  "sandbox.status.snapshot": { layer: "snapshot", phase: "sandbox" },
  "run.completed": { layer: "terminal", phase: "run" },
  "run.failed": { layer: "error", phase: "run" },
  "run.cancelled": { layer: "terminal", phase: "run" },
  "child_run.queued": { layer: "progress", phase: "orchestration" },
  "child_run.started": { layer: "progress", phase: "orchestration" },
  "child_run.awaiting_supervisor": { layer: "progress", phase: "orchestration" },
  "child_run.resumed": { layer: "progress", phase: "orchestration" },
  "child_run.message.created": { layer: "progress", phase: "orchestration" },
  "child_run.snapshot.updated": { layer: "snapshot", phase: "orchestration" },
  "child_run.deadline.extended": { layer: "progress", phase: "orchestration" },
  "child_run.wrapping_up": { layer: "progress", phase: "orchestration" },
  "child_run.cancelling": { layer: "progress", phase: "orchestration" },
  "child_run.completed": { layer: "terminal", phase: "orchestration" },
  "child_run.partial_completed": { layer: "terminal", phase: "orchestration" },
  "child_run.interrupted": { layer: "terminal", phase: "orchestration" },
  "child_run.timed_out": { layer: "terminal", phase: "orchestration" },
  "child_run.failed": { layer: "error", phase: "orchestration" },
  "child_run.cancelled": { layer: "terminal", phase: "orchestration" },
  "workflow.started": { layer: "progress", phase: "orchestration" },
  "workflow.snapshot.updated": { layer: "snapshot", phase: "orchestration" },
  "workflow.paused": { layer: "snapshot", phase: "orchestration" },
  "workflow.cancelling": { layer: "progress", phase: "orchestration" },
  "workflow.completed": { layer: "terminal", phase: "orchestration" },
  "workflow.partial_completed": { layer: "terminal", phase: "orchestration" },
  "workflow.failed": { layer: "error", phase: "orchestration" },
  "workflow.cancelled": { layer: "terminal", phase: "orchestration" },
  "scheduled_task.changed": { layer: "snapshot", phase: "orchestration" },
  "scheduled_task.run.started": { layer: "progress", phase: "orchestration" },
  "scheduled_task.run.completed": { layer: "terminal", phase: "orchestration" },
  "scheduled_task.run.failed": { layer: "error", phase: "orchestration" },
  "scheduler.status.snapshot": { layer: "snapshot", phase: "orchestration" },
  "request.invalid": { layer: "error", phase: "request" },
  "config.reloaded": { layer: "snapshot", phase: "config" },
  "config.failed": { layer: "error", phase: "config" },
  "config.snapshot": { layer: "snapshot", phase: "config" },
  "model.list.snapshot": { layer: "snapshot", phase: "config" },
  "provider.models.snapshot": { layer: "snapshot", phase: "config" },
  "provider.models.failed": { layer: "error", phase: "config" },
  "profile.snapshot": { layer: "snapshot", phase: "config" },
  "preset.snapshot": { layer: "snapshot", phase: "config" },
  "preset.failed": { layer: "error", phase: "config" },
  "system_tool.snapshot": { layer: "snapshot", phase: "config" },
  "mcp_server.snapshot": { layer: "snapshot", phase: "config" },
  "channel.status.snapshot": { layer: "snapshot", phase: "config" },
} as const satisfies Record<EventKind, { readonly layer: EventLayer; readonly phase: EventPhase }>;

export { EventSpecs } from "./generatedEventSpecs";

export const RunActivities = {
  PreparingContext: "preparing_context",
  InitializingRuntime: "initializing_runtime",
  SynchronizingContext: "synchronizing_context",
  EvaluatingContext: "evaluating_context",
  CompactingContext: "compacting_context",
  RunningAgentTurn: "running_agent_turn",
  GeneratingResponse: "generating_response",
  FinalizingResponse: "finalizing_response",
} as const;
export type RunActivity = (typeof RunActivities)[keyof typeof RunActivities];

export const RunActivityCategories = {
  Context: "context",
  Runtime: "runtime",
  Model: "model",
  Output: "output",
} as const;
export type RunActivityCategory = (typeof RunActivityCategories)[keyof typeof RunActivityCategories];

export const RunActivityStates = {
  Started: "started",
  Completed: "completed",
  Failed: "failed",
} as const;
export type RunActivityState = (typeof RunActivityStates)[keyof typeof RunActivityStates];

export const RunActivitySpecs = {
  preparing_context: {
    category: "context",
  },
  initializing_runtime: {
    category: "runtime",
  },
  synchronizing_context: {
    category: "context",
  },
  evaluating_context: {
    category: "context",
  },
  compacting_context: {
    category: "context",
  },
  running_agent_turn: {
    category: "model",
  },
  generating_response: {
    category: "output",
  },
  finalizing_response: {
    category: "output",
  },
} as const satisfies Record<RunActivity, { readonly category: RunActivityCategory }>;

export const AuthenticationSessionStates = {
  Disabled: "disabled",
  Anonymous: "anonymous",
  Authenticated: "authenticated",
} as const;
export type AuthenticationSessionState = (typeof AuthenticationSessionStates)[keyof typeof AuthenticationSessionStates];

export const ConfigSecretContract = {
  RedactedPlaceholder: "__senera_redacted_secret__",
} as const;

export const WebSocketCloseCodes = {
  AuthenticationRequired: 4401,
  AccessForbidden: 4403,
} as const;
export type WebSocketCloseCode = (typeof WebSocketCloseCodes)[keyof typeof WebSocketCloseCodes];

export const WebSocketCloseReasons = {
  AuthenticationRequired: "authentication_required",
  AccessForbidden: "access_forbidden",
} as const;
